# <center>算数运算符</center>

In [3]:
# 股票平均价 前五个交易日的均价
# 基本运算
(11 + 22 + 33 + 44 + 55)/5

33.0

# <center>变量和赋值运算符</center>

In [21]:
# 赋值
a = 3
print(a)
b = a
print(b)
print("-" * 10)
a,b,c = 1,2,3
print(a,b,c)

# 计算收入单价和数量
revernu = 1000
price = 20
number = revernu / price
print("-" * 10)
print(number)
print(type(number))
revernu += 500
print(revernu)

3
3
----------
1 2 3
----------
50.0
<class 'float'>
1500


# <center>整数和浮点数</center>

In [26]:
# 注意这个
print(0.1 + 0.1 + 0.1)

0.30000000000000004


- 在进行数学运算的时候要注意除零错误

# <center>比较运算符</center>

- 值应该是布尔值
- 注意not，相当于把布尔值进行了翻转

In [32]:
# 组合比较运算符计算
print(1 < 2 and 3 > 4)
print(1 < 2 or 3 > 4)
print(not 1 < 2 or 3 > 4)

False
True
False


# <center>字符串</center>

In [12]:
rst1 = 'this is a test'
print(rst1)
print(type(rst1))
# 一种方式使用两种引号
rst2 = "I'm a teacher"
print(rst2)
# 另一种方式
# \就是告诉解释器跳过这个'
rst3 = 'I\'m a teacher'
print(rst3)

this is a test
<class 'str'>
I'm a teacher
I'm a teacher


In [21]:
# 字符串的拼接
Frist_word = 'yes'
Second_word = 'and'
Three_word = 'no'
rst1 = Frist_word + ' '+ Second_word + ' ' + Three_word
print(rst1)
rst2 = Frist_word * 3
print(rst2)
print("-"  * 10)
# 字符串长度函数len()
print(len(rst2))

yes and no
yesyesyes
----------
9


In [24]:
# 做一个联系题，通过字符串长度判断输入的name是否正确，找出一个超长输入的字符串
Frist_name = 'fulajimier'
Family_name = 'pujing'
inputname = input('请输入一个名字')
if len(inputname) + 3 > len(Frist_name + Family_name):
    print("这个名字可能就是瞎输入的！")
else:
    print("这个名字可能是对的或者只是打错了！")

请输入一个名字sdf
这个名字可能是对的或者只是打错了！


# <center>类型和类型转换</center>

- 主要是布尔值的问题
    - True = 1
    - False = 0

# <center>字符串方法</center>

In [41]:
Mom_said = "Tom is a good boy"
print(Mom_said)
# 判断字符串是否都是小写方法-islower
rst1 = Mom_said.islower()
print(rst1)
# 查找字符串中指定字符的个数-count
rst2 = Mom_said.count('o')
print(rst2)
# 查找指定字符串首次出现在哪个位置-注意空格也是字符
rst3 = Mom_said.find('s')
print(rst3)

Tom is a good boy
False
4
5


# <center>列表</center>

In [21]:
List_one = [i for i in range(1,10)]
List_two = [1,2,3,4,'hello',True,False]
print(List_one)
print(List_one[5]) # 输出应该是6，注意索引从0开始
print(List_one[-1]) # 从右向左数第一个
print(List_one[-3]) # 输入应该是7
print(len(List_one)) # 列表长度
print(List_two)
print(len(List_two)) # 列表长度应该是7

# 打印出List_two的True,最后一位要减1，倒数第二位要减2
print(List_two[len(List_two) - 2])

[1, 2, 3, 4, 5, 6, 7, 8, 9]
6
9
7
9
[1, 2, 3, 4, 'hello', True, False]
7
True


## 列表切片

In [43]:
# 显示列表其中的一部分
list1 = [i for i in range(1,20)]
print(list1[8:17]) # 注意下标从0开始，8就是第9个元素
print(list1[8:]) # 从下标8开始到最后一个元素
print(list1[8:100]) # 如果下标超出，就打印到最后
print(list1[8:17:2])
print(list1[16:7:-2])

[9, 10, 11, 12, 13, 14, 15, 16, 17]
[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[9, 11, 13, 15, 17]
[17, 15, 13, 11, 9]


In [45]:
# 判断字符是否在列表中
# 结果是布尔值
list1 = [i for i in range(1,10)]
rst1 = 'a' in list1
rst2 = 'a' not in list1
print(rst1)
print(rst2)

False
True


## 列表和字符串的可变性

In [67]:
# 跟列表类似，字符串也可用通过下标访问其中的字符
rst5 = 'hello this is a test'
print(rst5[6])

t


- 注意一个明显的区别，字符串是不可变的，列表是可变的

In [66]:
list1 = [i for i in range(1,10)]
print(list1[3])
list1[3] = 88
print(list1[3])
rst1 = 'hello this is a test'
rst1[6] = 'tt'# 字符串是不能修改的会报错，想要修改字符串的值只能重新给字符串赋值

4
88


In [72]:
# 以下结果证明列表可以转换成字符串
list1 = [i for i in range(1,10)]
rst1 = str(list1)
print(type(rst1))

# 以下结果证明字符串也可以转换称为列表
rst2 = 'this is a test'
rst3 = list(rst2)
print(rst3)

<class 'str'>
['t', 'h', 'i', 's', ' ', 'i', 's', ' ', 'a', ' ', 't', 'e', 's', 't']


In [82]:
# 字符串的不可变性
# 注意另一个字符串的不可变性
rst1 = 'this'
rst2 = rst1
print(rst2)
rst1 = 'that'
print(rst2) # rst2结果没有发生变化，只有重新给rst2赋值，他的值才会发生变化。

# 列表的可变性
list1 = [i for i in range(1,10)]
list2 = list1
print(list2)
list1[6] = 77
print(list2) # 在这里可以很明显的看到list2的值发生了变化，
# 值的改变或者不改变跟python的执行顺序无关，只是因为字符串不可变而list可变。

this
this
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 77, 8, 9]


## 列表函数

In [98]:
list1 = [11,2323,22,1,111,23,5667,9,765,1,2,3]
print(len(list1)) # 列表元素个数
print(max(list1)) # 列表元素最大值
print(min(list1)) # 列表元素最小值
print(sorted(list1)) # 列表排序，从小到大
print(sorted(list1,reverse = True)) # 列表排序，从大到小
print(sorted(list1,reverse = False)) # 列表排序，从小到大

# 字符串排序-sorted
rst1 = ['C','Q','E','D','J','L','F','V']
rst2 = ['Caa','Qssss','Ewwwwewe','Da','J','Lasd','aasdF','AaadV']
print(sorted(rst1))
print(sorted(rst2)) # 结果可以看出字符串排序是按照首字母去进行排序，且先排大写，然后排小写
print(id(rst2))
print(id(sorted(rst2))) # 结果可以看出，列表是个新的列表，并非原列表。

12
5667
1
[1, 1, 2, 3, 9, 11, 22, 23, 111, 765, 2323, 5667]
[5667, 2323, 765, 111, 23, 22, 11, 9, 3, 2, 1, 1]
[1, 1, 2, 3, 9, 11, 22, 23, 111, 765, 2323, 5667]
['C', 'D', 'E', 'F', 'J', 'L', 'Q', 'V']
['AaadV', 'Caa', 'Da', 'Ewwwwewe', 'J', 'Lasd', 'Qssss', 'aasdF']
2032376617864
2032376617544


In [121]:
# 列表的join方法
list1 = ['1','2','3','4','5','6']
list2 = ''.join(list1) # 相当于用空白替代了逗号
list3 = '\n'.join(list1) # 相当于用\n这个换行符替代了逗号
print(list2)
print(type(list2))
print(list3)
print(type(list3))
rst1 = '~~~~~~~~~~~~~~~~~~'.join(list1)
print(rst1)

123456
<class 'str'>
1
2
3
4
5
6
<class 'str'>
1~~~~~~~~~~~~~~~~~~2~~~~~~~~~~~~~~~~~~3~~~~~~~~~~~~~~~~~~4~~~~~~~~~~~~~~~~~~5~~~~~~~~~~~~~~~~~~6


In [1]:
# 列表的append方法
list1 = ['this','is','a']
ele1 = 'test'
list1.append(ele1)
print(list1)
# append不能一次添加两个元素！

['this', 'is', 'a', 'test']


# <center>元组</center>

- tuple
- 相比于list是一个不可变的集合

In [3]:
tuple1 = (10,20)
print(tuple1[0],tuple1[1])

10 20


In [5]:
# 元组不一定需要括号表示
tuple2 = 1,2,3,4
print(type(tuple2)) # 可以看到不带括号类型也是一个tuple

<class 'tuple'>


In [7]:
# 元组解包
rst1 = 4,5,6
chang,kuan,gao = rst1
print(chang)
print(kuan)
print(gao)

4
5
6


In [9]:
# format
print("长： {} 宽：{} 高：{} 体积是{}".format(chang,kuan,gao,chang * kuan * gao))

长： 4 宽：5 高：6 体积是120


# <center>集合和列表去重</center>

- 集合 set是可变的，但是没有顺序，不会有重复的元素。

In [18]:
# 把列表转换成集合，去掉重复数据
list1 = ['11','22','33','444','22','111','1','11','1','77','7']
tuple1 = '11','22','33','444','22','111','1','11','1','77','7'
print(list1)
list1 = set(list1) # 可以将list转换成set，直接去掉了重复的数据
print(list1)

print(tuple1)
tuple1 = set(tuple1) # 可以将tuple转换成set，直接去掉了重复的数据
print(tuple1)

['11', '22', '33', '444', '22', '111', '1', '11', '1', '77', '7']
{'444', '1', '22', '7', '77', '33', '11', '111'}
('11', '22', '33', '444', '22', '111', '1', '11', '1', '77', '7')
{'444', '1', '22', '7', '77', '33', '11', '111'}


In [46]:
# 检测集合中是否存在元素
print(22 in tuple1)
print('22' in tuple1)
print('111' not in tuple1)
# 集合的add添加
tuple3 = {1,2,3,4,5,6,7,8}
tuple3.add(9)
print(tuple3)
# pop弹出元素
tuple3.pop()
print(tuple3)

False
True
False
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{2, 3, 4, 5, 6, 7, 8, 9}


# <center>字典</center>

- 有键有值

In [62]:
# 字典举例
dict1 = {'name':'doudou','age':18,'sex':'nan'}
print(dict1['age']) # 根据键打印值
print(dict1.items()) # 枚举全部键值
# get方法获取键的值，不会报错！
print(dict1.get('name')) # 通过字典的get方法，也可以检查键的值
print(dict1.get('balabala')) # 并且如果没有指定的键也不会报错，返回None！
#以下这种方式判定，字典中有没有指定键的值存在，利用get方法。
rst1 = dict1.get('this')
print(rst1 is None)
print(rst1 is not None)
# get自定义返回值
rst2 = dict1.get('qishi','没有这个键') # get后第二个参数为自定义的返回值
print(rst2)

18
dict_items([('name', 'doudou'), ('age', 18), ('sex', 'nan')])
doudou
None
True
False
没有这个键


In [68]:
# = ， == ， is
a = [1,2,3,4,5]
b = a
c = [1,2,3,4,5]
print(a == b , a == c , b == c)
print(a is b,b is a,c is b,c is a) # 这里可以看到is和=是不一样的

True True True
True True False False


# <center>复合数据结构</center>

In [91]:
# 
fuhe1 = {'people':{'name':'doudou','age':18,'sex':'nan'},'work':'gongchengshi','zhuangtai':'good'}
print(fuhe1.items())
rst1 = fuhe1['people']['name'] # 获取字典内的字典
print(rst1) 

dict_items([('people', {'name': 'doudou', 'age': 18, 'sex': 'nan'}), ('work', 'gongchengshi'), ('zhuangtai', 'good')])
doudou


# <center>控制流</center>

In [95]:
# 条件语句 if elif else
a = 1
b = 0
if b == 0 :
    a += 1
print(a)

2


# <center>复杂的布尔表达式</center>

In [97]:
chang = 11
kuan = 2
gao = 3
if 100 < chang * kuan * gao < 10000:
    print("ok")
else:
    print("不 ok")

不 ok


# <center>循环</center>

## for循环

In [117]:
# 将list的首字母大写
list1 = ['this','is','a','test']
list2 = []
for i in list1:
    list2.append(i.title())
print(list2)

['This', 'Is', 'A', 'Test']


# <center>range函数</center>

In [136]:
# 循环体中执行10次
for i in range(3):
    print('hello')
# range生成列表
list1 = [i for i in range(1,10)]
print(list1)
# range中的参数
rst1 = [i for i in range(1,100,3)]
print(rst1)

hello
hello
hello
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]


In [144]:
# 利用列表的长度进行循环，将列表元素的首字母大写。
list1 = ['dog','monkey','cat','tiger','elephant']
for index in range(len(list1)):
    list1[index] = list1[index].title()
print(list1)


['Dog', 'Monkey', 'Cat', 'Tiger', 'Elephant']


In [149]:
# 将名字小写只有首字母大写，空格替换成下划线。
names = ['HAN MEIMEI','LI LEI','XIAO MING','ZHANG QIU','HA LI','PI TE','AI HUA']
list1 = []
for name in names:
    list1.append(name.lower().title().replace(" ","_"))
print(list1)

['Han_Meimei', 'Li_Lei', 'Xiao_Ming', 'Zhang_Qiu', 'Ha_Li', 'Pi_Te', 'Ai_Hua']


# <center>字典迭代</center>

In [9]:
# 迭代这个字典
dict1 = {'name1':'HAN MEIMEI','name2':'LI LEI','name3':'XIAO MING','name4':'ZHANG QIU',
         'name5':'HA LI','name6':'PI TE','name7':'AI HUA'}
print(dict1.items())
for key,value in dict1.items(): # 注意需要循环字典的.items()方法
    print("这是第{}个人，他的名字是{}".format(key.replace("name",""),value))
# 需要注意结果，python有的版本字典是有序的，有的版本字典是无序的。

dict_items([('name1', 'HAN MEIMEI'), ('name3', 'XIAO MING'), ('name2', 'LI LEI'), ('name6', 'PI TE'), ('name7', 'AI HUA'), ('name5', 'HA LI'), ('name4', 'ZHANG QIU')])
这是第1个人，他的名字是HAN MEIMEI
这是第3个人，他的名字是XIAO MING
这是第2个人，他的名字是LI LEI
这是第6个人，他的名字是PI TE
这是第7个人，他的名字是AI HUA
这是第5个人，他的名字是HA LI
这是第4个人，他的名字是ZHANG QIU


# <center>while循环</center>

In [12]:
# while循环
list1 = [i for i in range(1,13)]
list2 = []
while sum(list2) <= 50:
    print(list2)
    list2.append(list1.pop()) # 将list1的内容pop拿出，append到list2中，当list2超过50，停止循环。
print("-" * 20)
print(list1)
print(list2)
    

[]
[12]
[12, 11]
[12, 11, 10]
[12, 11, 10, 9]
[12, 11, 10, 9, 8]
--------------------
[1, 2, 3, 4, 5, 6]
[12, 11, 10, 9, 8, 7]


In [5]:
# break中断
# 这是一个有条件结束否则无限的循环
while True:
    text1 = input("请输入字符")
    if text1 == 'q': # 当输入q的时候停止循环
        break
    else:
        print(text1.capitalize()) # 否则继续循环并且将输入内容首字母大写

请输入字符a


In [26]:
# continue 跳过循环

while True:
    number1 = input("请输入内容") # 注意这个如果放在循环体外面，就会无限循环卡死！
    if number1 == 'q': # 当输入q的时候结束循环
        break
    else:
        number2 = int(number1)
        if number2 % 2 == 0:
            print('输入的字符{}是一个偶数'.format(number2))
            continue
        else:
            print('输入的字符{}是一个奇数'.format(number2))

请输入内容1
输入的字符1是一个奇数
请输入内容2
输入的字符2是一个偶数
请输入内容q


# <center>zip迭代器</center>

- 相当于迭代之后再组合

In [40]:
# zip迭代器
# 将两个列表组合在一起
names = ['zhang qiu','xiao wang','qian duoduo','sun xiaogang','liu mei','a da','lao er','xing xing']
ages = [11,12,13,14,17,11,19,21]
list(zip(names,ages)) # 以list方式把zip迭代器的东西展示出来，也可以用set
# 如果两个列表的顺序对不上也不会报错

[('zhang qiu', 11),
 ('xiao wang', 12),
 ('qian duoduo', 13),
 ('sun xiaogang', 14),
 ('liu mei', 17),
 ('a da', 11),
 ('lao er', 19),
 ('xing xing', 21)]

In [62]:
# 打印出顺序id和名字
names = ['                   zhang qiu','xiao wang','qian duoduo','sun xiaogang','liu mei','a da','lao er','xing xing']
for i,name in zip(range(len(names)),names): # range(len(names))的意思是先计算出names的长度，然后用range函数，计算0-x。
    print("出场顺序{}名字{}".format(i + 1,name).replace(" ",""))

出场顺序1名字zhangqiu
出场顺序2名字xiaowang
出场顺序3名字qianduoduo
出场顺序4名字sunxiaogang
出场顺序5名字liumei
出场顺序6名字ada
出场顺序7名字laoer
出场顺序8名字xingxing


In [81]:
# 上面例子简易方式，直接利用函数enumerate即可
names = ['zhang qiu','xiao wang','qian duoduo','sun xiaogang','liu mei','a da','lao er','xing xing']
print(list(zip(enumerate(names,1)))) # 注意1是从几开始，默认是从0开始
print("-" * 20)
# 上面的有好几个括号，应该是不对，可以用enumerate直接替代range试一下
for i,name in enumerate(names,1):
    print(i,name)

[((1, 'zhang qiu'),), ((2, 'xiao wang'),), ((3, 'qian duoduo'),), ((4, 'sun xiaogang'),), ((5, 'liu mei'),), ((6, 'a da'),), ((7, 'lao er'),), ((8, 'xing xing'),)]
--------------------
1 zhang qiu
2 xiao wang
3 qian duoduo
4 sun xiaogang
5 liu mei
6 a da
7 lao er
8 xing xing


In [94]:
# 反向zip
names = ['zhang qiu','xiao wang','qian duoduo','sun xiaogang','liu mei','a da','lao er','xing xing']
ages = [11,12,13,14,17,11,19,21]
list1 = list(zip(names,ages))
print(list1) # 现在list1已经变成了有一对元素的列表，现在把他拆开 ，只留name
names1,ages1 = list(zip(*list1)) # 这就是反向zip，依然使用zip函数，但是zip函数里多个一个*号
names1 = list(names1)
print(type(names1))

[('zhang qiu', 11), ('xiao wang', 12), ('qian duoduo', 13), ('sun xiaogang', 14), ('liu mei', 17), ('a da', 11), ('lao er', 19), ('xing xing', 21)]
<class 'list'>


## 练习题

In [39]:
# 购物test
# 输入按钮输入商品名称和数量，然后从已有列表中查找对应的金额，计算总价，打印出一个购物清单，
# 并且要加上添加进去的时间。
import time
shangpinliebiao = {'苹果':'1.2','菠萝':'2.4','香蕉':'3.3','葡萄':'5.6',
                   '草莓':'10.12','西瓜':'3.8','橘子':'2.2','桃子':'7.1'}
srmingcheng = [] #商品名称
shangpindanjia = [] # 商品单价
srshuliang = [] # 商品数量
danpinzongjia = [] # 单品总价
currenttime = [] # 当前时间
quanbuzongjia = [] #全部总价


while True:
    inputmingcheng = input("请输入想要购买的商品名称：")
    if inputmingcheng in shangpinliebiao :
        # 查询输入商品的价格是多少
        cxshangpinjiage = shangpinliebiao[inputmingcheng]
        # 输入想要购买的数量
        inputshuliang = int(input("请输入想要购买该商品的数量："))
        # 计算单品总价
        jsdanpinzongjia = round(inputshuliang * float(cxshangpinjiage),2)
        # 查询当前时间
        cxdangqianshijian = time.strftime("%Y{}%m{}%d %H:%M:%S",time.localtime()).format("年","月","日")
        # 名称加进列表
        srmingcheng.append(inputmingcheng)
        # 单价加进列表
        shangpindanjia.append(cxshangpinjiage)
        # 数量加进列表
        srshuliang.append(inputshuliang)
        # 单品总价加进列表
        danpinzongjia.append(jsdanpinzongjia)
        # 当前时间加进列表
        currenttime.append(cxdangqianshijian)
        # 计算全部总价
        quanbuzongjia = sum(danpinzongjia)
    elif inputmingcheng == 'q':
        print("结束购物！")
#         print(srmingcheng)
#         print(srshuliang)
#         print(shangpindanjia)
#         print(danpinzongjia)
#         print(currenttime)
#         print(quanbuzongjia)
        listxiangdan = list(zip(srmingcheng,srshuliang,shangpindanjia,danpinzongjia,currenttime))
        scshipinmingcheng,scshipinshuliang,shuchushipindanjia,shuchudanpinzongjia,shuchucurrenttime = zip(*listxiangdan)
        print('''
        名称 ：{0}
        数量 ：{1}
        单价 ：{2}
        单品总价 ：{3}
        采购时间 ：{4}
        全部总价 ：{5}
        '''.format(scshipinmingcheng,scshipinshuliang,shuchushipindanjia,shuchudanpinzongjia,shuchucurrenttime,quanbuzongjia))
        break
    else:
        print("输入的商品名称有误，请重新输入！")


请输入想要购买的商品名称：苹果
请输入想要购买该商品的数量：1
请输入想要购买的商品名称：q
结束购物！

        名称 ：('苹果',)
        数量 ：(1,)
        单价 ：('1.2',)
        单品总价 ：(1.2,)
        采购时间 ：('2020年03月02 17:54:30',)
        全部总价 ：1.2
        


In [43]:
# 利用zip将列表组合成字典
list1 = [1,2,3,4,5]
list2 = ['a','b','c','d','e']
dict(zip(list1,list2))

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e'}

# <center>列表推导式</center>

In [13]:
# 把1-10加进一个空的列表
list1 = []
for i in range(1,11):
    list1.append(i)
print(list1)
# 另一种方式
list2 = list(range(1,11))
print(list2)
# 另外一种方式
list3 = [i for i in range(1,11)]
print(list3)

# 带条件的列表推导式
list4 = [i * i # 整个列表是计算 i * i
         if i % 2 == 0 # 条件是如果i是个偶数就执行i * i
         else i + 10 # 否则就把i + 10
         for i in range(1,10) # i的原始值是1 - 9
    ]
print(list4)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[11, 4, 13, 16, 15, 36, 17, 64, 19]


# <center>补充函数</center>

- split() 一个在数据处理中有重要地位的函数，将字符串拆分成列表，但是注意只能拆分字符串。

In [25]:
# split() 拆分一个字符串，中间有空格就拆分，形成一个list
text1 = 'this is a test'
rst1 = text1.split()
print(rst1)
print(type(rst1))
# splitlines是将多行的字符串拆分成list
text2 = '''
this is test1
this is test2
'''
rst2 = text2.splitlines()
print(rst2)
print(type(rst2))

# \t和\n的举例
text3 = 'This \t is \t a \t Test' # 很奇怪 这个版本拆分不出来。。
text4 = 'this\nis\na\ntest'
rst3 = text3.splitlines()
print(rst3)
print(type(rst3))
rst4 = text4.splitlines()
print(rst4)
print(type(rst4))

# split可以带参数，这样就会以指定字符作为拆分标记
text5 = 'this:is:a:test'
rst5 = text5.split(":")
print(rst5)
print(type(rst5))

# split可以带两个参数，第二个参数是将字符串切成列表时分为几部分，如果参数是1就是两部分，
# 从第一个指定分隔符开始切分，后面不再切分
text6 = 'this:is:a:test'
rst6 = text5.split(":",1)
print(rst6)
print(type(rst6))

['this', 'is', 'a', 'test']
<class 'list'>
['', 'this is test1', 'this is test2']
<class 'list'>
['This \t is \t a \t Test']
<class 'list'>
['this', 'is', 'a', 'test']
<class 'list'>
['this', 'is', 'a', 'test']
<class 'list'>
['this', 'is:a:test']
<class 'list'>


## 列表推导式练习题

In [11]:
# 从客户清单中提取出他的姓,并且首字母大写
names = ['li lei','han meimei','gao qiu','zhao zhen','qian duoduo','sun zi','liu xiang']
strnames1 = [name.split() for name in names] # for name in names是先将names列表循环，然后name.split()是将列表拆分
strnames2 = [name.split()[0].title() for name in names]# 拆分后的每一组取下标为0的元素保留,用title方法将首字母大写
print(strnames1)
print(strnames2)

[['li', 'lei'], ['han', 'meimei'], ['gao', 'qiu'], ['zhao', 'zhen'], ['qian', 'duoduo'], ['sun', 'zi'], ['liu', 'xiang']]
['Li', 'Han', 'Gao', 'Zhao', 'Qian', 'Sun', 'Liu']


In [31]:
# 信贷打分筛选
# 挑选出信用质量大于60分的人
scores_card = {'li lei':61,'han meimei':76,'gao qiu':80,'zhao zhen':91,'qian duoduo':32,'sun zi':59,'liu xiang':48}
ok_card = [name for name,score in scores_card.items() if score >= 60]
print(ok_card)

['li lei', 'han meimei', 'gao qiu', 'zhao zhen']


# <center>自定义函数</center>

- 自定义函数的构成：
    - def关键字
    - add是函数名称
    - num1和num2是参数，可有可没有
    - 函数主体，可以没有
    - 返回值，默认是None

In [47]:
# 自定义函数加减乘除
def add(num1,num2):
    pass
    return num1 + num2
def jian(num1,num2):
    return num1 - num2
def cheng(num1,num2):
    return num1 * num2
def chu(num1,num2):
    return num1 / num2
print(add(6,1))
print(jian(6,1))
print(cheng(6,1))
print(chu(6,1))
# 
print("-" * 20)
#自定义函数的默认参数，可以给参数赋值
def def1(a,b = 11):
    return a + b
print(def1(12)) # 结果变成了12 + 11
print(def1(12,3)) #结果变成了12 + 3

7
5
6
6.0
--------------------
23
15


In [92]:
# test-计算贷款到期剩余天数
import math
def daikuanshengyu(days):
    year = days // 365 # 将天数换算成年-注意 // 代表整除，不足一年就是0，超过一年就是1
    month = (days % 365 ) // 30
    day = (days % 365) % 30
    shengyutianshu = "{}天转换成剩余天数{}年{}月{}天".format(days,year,month,day)
    print(year,month,day)
    return shengyutianshu
print(daikuanshengyu(957))

2 7 17
957天转换成剩余天数2年7月17天


# <center>写文档</center>

- 在代码中使用""" xxxxx """的方式写一个文档
- 在调用的时候使用 .__doc__的方式调用即可打印文档

In [104]:
def PE(Price,Earning):
    """这个PE函数的作用是。。。
       
        INPUT: 
        Price：作用是
        Earning：作用是
        
        OUTPUT：
        PE：Price/Earning
    """
    PE = Price/Earning
    return print(PE)

PE(50,20)
PE.__doc__.replace(" ","").replace("\n","")

2.5


'这个PE函数的作用是。。。INPUT:Price：作用是Earning：作用是OUTPUT：PE：Price/Earning'

# <center>Lambda表达式</center>

- 相当于创建一个匿名函数，快速创建，直接调用。
    - 对于高阶函数，Lambda比较易用

In [112]:
# 写一个自定义函数，这样很麻烦，比如说写一个做加法的函数
def add(a,b):
    rst1 = a + b
    return print(rst1)
#########################################################
print("-" * 20)
# 利用lambda表达式
supper_add1 = lambda num1,num2:num1 + num2
supper_add2 = lambda num1,num2:print(num1 + num2)
supper_add1(1,2)
supper_add2(1,2)
# 利用Lambda表达式做一个乘法
super_cheng = lambda num1,num2:print(num1 * num2)
super_cheng(2,3)

--------------------
3
6


## 高阶内置函数

In [11]:
# 高阶内置函数- filter()

# 名字列表
names = ['li lei','han meimei','gao qiu','zhao zhen','qian duoduo','sun zi','liu xiang']

# 做一个白名单规则，名字长度不超过8进白名单
def white_name(name):
    return len(name) < 8
# filter 其中white_name是需要过滤的条件，后面是一个可迭代的对象
white_name_list = list(filter(white_name,names))
print(white_name_list)


#下面其中gao qiu这个名字被拉进了黑名单，但是还是在列表中，怎么把它去除掉过滤掉gao qiu的名字
def panduan_gaoqiu (name):
    return name == 'gao qiu'
black_name_list = list(filter(panduan_gaoqiu,names))
print(black_name_list)
#####################################
print("_" * 20)
# 利用lambda实现上面的功能
white_name_list_lambda= (list(filter(lambda x:len(x)< 8,names)))
print(white_name_list_lambda)
black_name_list_lambda = list(filter(lambda x:x == 'gao qiu',names))
print(black_name_list_lambda)

['li lei', 'gao qiu', 'sun zi']
['gao qiu']
____________________
['li lei', 'gao qiu', 'sun zi']
['gao qiu']


In [5]:
# 高阶内置函数map()
# 利用平方的函数，将list1的全部进行平方操作
def pingfang(num1):
    return num1 ** 2
list1 = [i for i in range(1,10)]
rst1 = list(map(pingfang,list1)) # 需要注意的是map返回是可迭代的，需要把它迭代出来，或者把它变成一个list展示出来
print(rst1)

# 利用lambda表达式实现上面功能
rst1_lambda = list(map(lambda x:x**2,list1))
print(rst1_lambda)

[1, 4, 9, 16, 25, 36, 49, 64, 81]
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [3]:
# 假设列表中存放的是不同地区每个机构的评分表
# 计算每个地区平均的评分
score_card1 = [[2,3,4,1,2,3,5,6,5,2],[5,6,7,5,5,7,6,7,5,6],[8,9,8,7,8,9,8,9,9,8]]

# 平均数函数
def pingjun(score):
    return sum(score)/len(score)

pingjun_card = list(map(pingjun,score_card1))
print(pingjun_card)

# 利用lambda实现上述功能
pingjun_lambda = list(map(lambda x:sum(x)/len(x),score_card1))
print(pingjun_lambda)


[3.3, 5.9, 8.3]
[3.3, 5.9, 8.3]


# <center>迭代器和生成器</center>

- iterator ：迭代器
    - 迭代器可以返回一个可迭代的对象比如list
- generator ：生成器
    - 生成器可以用函数的方式创建出迭代器

## 迭代器

- 每次都可以返回一个对象元素的对象

In [26]:
# enumerate就是一个迭代器-功能是列举，报数
list1 = [1,2,3,4,5,6,7,8,9]
for i in enumerate(list1,1):
    print(i)
rst1 = enumerate(list1) # 从结果可以看出，结果输入的是一个数据流
print(rst1)
rst2 = list(enumerate(list1)) # 需要放到list或其他的序列中才可以展示
print(rst2)

(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 5)
(6, 6)
(7, 7)
(8, 8)
(9, 9)
[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9)]


## 生成器

- 注意循环的返回不是retrun 而是yield！
    - 也可以此去判断是否是一个生成器？

In [36]:
# 使用生成器生成迭代器
# 自己创造一个range函数
def my_range(x):
    '''
    my_range:这个函数是我自己写的一个函数，跟range同等功能。
    '''
    a = 0
    while a < x:
        yield a # 需要注意：先返回，再加1，否则就从1开始了
        a += 1
list1 = [i for i in my_range(10)]
print(list1)
print(my_range.__doc__)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

    my_range:这个函数是我自己写的一个函数，跟range同等功能。
    


- 上面的生成器写完时，就会返回一个迭代器

In [44]:
print(my_range(11)) # 这里可以看到类型是generator 也就是一个生成器
print(list(my_range(11))) # 将数据流打印出来

<generator object my_range at 0x0000016FF19B2468>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


- 相比于写一个for循环来说使用生成器的速度执行一个1-10会很快。

## 自己编写一个迭代器-my_enumerate

In [16]:
list_name = ['li lei','han meimei','gao qiu','zhao zhen','ming ren','a kun']
def my_enumerate(list_x,id_start =0):
    count = id_start
    a = 0
    for i in list_x:
        yield count,i
        count += 1
        
# print(my_enumerate(list_name)) # 结果可知这是一个生成器
print(list(my_enumerate(list_name,2)))

for i,name in my_enumerate(list_name):
    print( i+ 1,name)
    

[(2, 'li lei'), (3, 'han meimei'), (4, 'gao qiu'), (5, 'zhao zhen'), (6, 'ming ren'), (7, 'a kun')]
1 li lei
2 han meimei
3 gao qiu
4 zhao zhen
5 ming ren
6 a kun


- 因为考虑到计算机性能个问题，假设range(1,100)计算机一次处理不了，这个时候就要分步执行。
- 可以利用自己创建的生成器去完成功能。

In [67]:
import time
# 自己创建一个切分的函数
def qiefen(xunhuanti,size = 20): 
    for i in range(0,len(xunhuanti),size): # 从0开始，到循环体的长度的值
        time.sleep(1) # 循环间隔1秒，便于展示
        yield xunhuanti[i:i+size] # 切分成列表，从i到i+size
        
for i in qiefen(range(1,100)):
    print(list(i))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
[41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
[61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]
[81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


# <center>异常和错误</center>

In [5]:
# 例子1
try:
    a = 10
    print(a/0)
except: # 或者直接这样
# except ZeroDivisionError:
    print("不能除0！")
else:
    print("只有正常执行才会执行else中的内容!")
finally:
    print("程序执行完毕！")

# 例子2
while True:
    try:
        num1 =  int(input("请输入一个数字！"))
        break
    except:
        print("需要输入一个数字，否则不能停止！")
    finally:
        print("程序执行完成！")

不能除0！
程序执行完毕！
请输入一个数字！1
程序执行完成！


# <center>文件操作</center>

In [12]:
# 读取文件
with open("C:\\Users\\Work-PC\\Desktop\\python_text.text","r",encoding='utf-8') as text1:
    rst1 = text1.read()
    print(rst1)
    text1.close()# 记得关掉文档


梦后楼台高锁，酒醒帘幕低垂。
去年春恨却来时。落花人独立，微雨燕双飞。
记得小蘋初见，两重心字罗衣。
琵琶弦上说相思。当时明月在，曾照彩云归。

梦后楼台高锁，酒醒帘幕低垂。
去年春恨却来时。落花人独立，微雨燕双飞。
记得小蘋初见，两重心字罗衣。
琵琶弦上说相思。当时明月在，曾照彩云归。



In [11]:
# 写入文件- w会覆盖原有文件 +是读取和写入 a是添加不会覆盖原有
text_text = '''
梦后楼台高锁，酒醒帘幕低垂。
去年春恨却来时。落花人独立，微雨燕双飞。
记得小蘋初见，两重心字罗衣。
琵琶弦上说相思。当时明月在，曾照彩云归。
'''
with open("C:\\Users\\Work-PC\\Desktop\\python_text.text","+a",encoding='utf-8') as text1:
    text1.write(text_text)
    text1.close()
    

In [15]:
# 创建新文件并写入- x创建
text_text = '''
梦后楼台高锁，酒醒帘幕低垂。
去年春恨却来时。落花人独立，微雨燕双飞。
记得小蘋初见，两重心字罗衣。
琵琶弦上说相思。当时明月在，曾照彩云归。
'''
with open("C:\\Users\\Work-PC\\Desktop\\python_text_1.text","+x",encoding='utf-8') as text1:
    text1.write(text_text)
    text1.close()

# <center>导入</center>

In [17]:
# 使用import导入
import os
os.getcwd()

'C:\\Users\\Work-PC\\Documents\\Python'

- 标准库

# <center>shell</center>

- shell:壳：和计算机进行交互的接口
- kernel：内核

- 通常shell分为两类：命令行和图形界面

linux echo就是输出
```
$ echo hello
hello
```
命令包括：ls、ll、cd、cd..、pwd


- cd~ 可以回到系统默认位置
- ll 后面可以跟路径，这样就能指定路径查看文件

`mv bashtest/*.abc bashtest1`批量移动文件


- curl
    - curl 'www.baidu.com'
    - curl -L 'www.baidu.com' 有的网站有重定向 需要使用到-L参数
    - curl -L -o d:/bashtest/baidu.html 'www.baidu.com' 将网页储存到本地

- nano一个笔记本

- `grep test test.abc` grep可以这样使用，前面是要搜索的词 后面是文件名

- `curl 'www.qq.com' -L |grep qq |wc -l` 计数 qq网页有多少个qq字符

- 查看说明书 man x
    - 比如 man yum

# <center>git命令</center>

- 比较文件内容
    - `diff abc1.test abc2.test`
- 建立一个本地的仓库做一个版本控制
    - git init # git 初始化，会生成一个.git文件夹 相当于本地仓库
    - git add abc1.test # 跟踪文件
    - git status # 显示文件状态
    - git commit # 提交文件
    
    - git log # 查看git的log
    - git diff {两次修改log的id} # 看看两次提交有什么不同
    - gif diff # 直接对比工作区和缓存区的内容
    - git diff --staged # 对比缓存区和仓库的区
    - git reset --hard # 直接将本地文件恢复到仓库的最后一次提交内容，相当于快速恢复。
    - git commit -m "xxxxxx" # 快捷写说明

- Braching # 分支 非线性更新
    - git branch # 查看当前路线
    - git branch test_version # 创建一个分支
    - git checkout test_version # 切换到另一个分支
    - git merge master test_version # 自动合并分支
    
- 合并可能会产生冲突
    - 需要手动同步更改

## git hub

- git hub push
    - git remote # 建立远端链接，需要先git init初始化,并建立本地仓库
        - git remote add origin https://github.com/lzhedoudou/Jupyter.git
        - git push -u origin master

- git hub pull#
    - git pull origin master # 从云端仓库down下来

- 可以将其他人的代码fork到本地
    - 先fork，然后 git clone https://github.com/lzhedoudou/ItChat.git

# <center>数据可视化</center>

- matplotlib
    - 例子位置：pychram

# <center>类和对象</center>

- class 类
    - object 对象 万物皆是对象

In [11]:
# 创建一个类
class User():
    pass
rst1 = User()
rst1.name = 'doudou'
rst1.age = 18
rst1.sex = 'girl'
print(rst1.name,rst1.age,rst1.sex)

doudou 18 girl


In [13]:
import datetime as dt
import time as time
# 类的实例化
class Person():
    '''
        这是一个拆分姓名根据生日计算年龄的类
    '''
    def __init__(self,name,brithday,sex): # 这个是在类中必须存在的，注意要写
        self.name = name
        self.brithday = brithday
        self.sex = sex
        # 将全名拆开 分为姓和名
        name_chaifen = name.split(" ")
        self.xing = name_chaifen[0]
        self.ming = name_chaifen[-1] # 为什么是-1 因为要保证是最后一位，有可能名字中间有空格
        return None
    # 根据输入的生日计算出年龄
    def jisuan_age(self):
        today = dt.date.today() # 获取当前日期
        year = int(self.brithday[0:4]) # 获取输入的birthday的下标区间字符，注意需要转换成int类型
        month = int(self.brithday[4:6]) # 获取输入的birthday的下标区间字符，注意需要转换成int类型
        day = int(self.brithday[6:8]) # 获取输入的birthday的下标区间字符，注意需要转换成int类型
        brithday_date = dt.date(year,month,day) # 转换成date类型 便于下一步计算
        age_day = (today -brithday_date).days /365 # 计算差值，注意.days是datetime自带的方法
        return int(age_day) # 用int函数将浮点数转换为整数
rst1 = Person('li zhe dou','19901127','nan')
print("我的姓是{}名字是{}今年{}岁性别{}".format(rst1.xing,rst1.ming,rst1.jisuan_age(),rst1.sex))
print(Person.__doc__)


我的姓是li名字是dou今年29岁性别nan

        这是一个拆分姓名根据生日计算年龄的类
    


# <center>numpy,pandas</center>

- numpy和pandas进行数据处理，数据处理完成后用matplotlib进行数据可视化
    - pandas基于numpy 进行了改进

## numpy

In [45]:
import numpy as np
list1 = [i for i in range(1,10)]
list2 = [i for i in range(10,1,-1)]
list3 = [i for i in range(11,20)]
# print(list1,type(list1))
print(type(list2))
V = np.array(list1) # 用array就可以将一个列表变成array格式
M = np.array([list1,list2])
print(V,type(V)) # 像列表，但是没有逗号
print(M)
print(V.shape)
print((M.shape)) # 2就是有两行 9是代表有九列
H = np.array([list1,list2,list3],dtype = float) # 强制变为float型
print(H.shape) # 结果进一步证明了ndarray代表了行和列
print(np.shape(H)) # 跟上面是一样的
print("-" * 20)
print(np.size(H)) # 共有27个元素

print(V.dtype,M.dtype,H.dtype) # 内部的数据类型查看
H[1,0] = 21# 修改ndarray中内容
print(H)

<class 'list'>
[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6  7  8  9]
 [10  9  8  7  6  5  4  3  2]]
(9,)
(2, 9)
(3, 9)
(3, 9)
--------------------
27
int32 int32 float64
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [21.  9.  8.  7.  6.  5.  4.  3.  2.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19.]]


- array跟list不同，只能装同一类型的数据。

In [90]:
# array切分操作 - 相当于有一个矩阵，切一个区域出来
# 如何将2，3，6，7切出来
import numpy as np
a= np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
print(a)
b = a[0:2,1:3] # 根据输出结果0：2表示切分第1行到第2行（注意从0开始包左不包右） 1：3表示列元素 从第2个元素到第3个元素
print(b)

# 精准定位到7
print(b[1,1])
# 将7的值变为9999
b[1,1] = 9999
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
7
[[   2    3]
 [   6 9999]]


In [65]:
import numpy as np
# 生成np数据 注意双括号
c = np.zeros((2,5)) # 都是0，两行5列
print(c)
d = np.ones((3,6)) # 都是1，三行六列
print(d)

e =np.full((6,7),'999') # 填充999，6行七列
print(e)

f = np.eye(10) # 跟matlab创建矩阵一样，只有对角线是1，10行10列
print(f)

g = np.random.random((2,3)) # 两行三列，内容随机生成
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[['999' '999' '999' '999' '999' '999' '999']
 ['999' '999' '999' '999' '999' '999' '999']
 ['999' '999' '999' '999' '999' '999' '999']
 ['999' '999' '999' '999' '999' '999' '999']
 ['999' '999' '999' '999' '999' '999' '999']
 ['999' '999' '999' '999' '999' '999' '999']]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0.10543411 0.18778322 0.86856291]
 [0.43381938 0.92208446 0.29783261]]


- 有个问题要注意下，如果是赋值的话，当被赋值的变量的元素发生改变，那原array也会发生变化，如下所示：

In [11]:
import numpy as np
h = np.array([[1,2],[3,4],[5,6],[7,8]])
i = h[0:2,1:2] # 将2和4切出来，0:2表示切第1行，1:2表示切第二列
print(h)
print("-" * 20)
print(i)
print(i[1,0]) # 将4打印出来 
i [1,0] = 888 #将4修改成888，再打印h和i
print(h) # 结果可以发现h确实被改过来了

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------
[[2]
 [4]]
4
[[  1   2]
 [  3 888]
 [  5   6]
 [  7   8]]


In [12]:
import numpy as np
j = np.array([[1,2],[3,4],[5,6],[7,8]])
k = np.array(j[0:2,1:2]) # 这是生成新的arrry
print(j)
print("-" * 20)
print(k)
print("-" * 20)
print(k[1,0]) # 将4打印出来 
k [1,0] = 888 #将4修改成888，再打印
print(j) # 通过结果可以发现k变了，但是j没变，这就是和上面例子的区别。
print(k) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------
[[2]
 [4]]
--------------------
4
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[  2]
 [888]]


In [30]:
# 用另一种index方法构建array
# 把 245抽出来
import numpy as np
l = np.array([[1,2],[3,4],[5,6],[7,8]])
print(l)
m = l[[0,1,2],[1,1,0]] # 相互对应，第一行第二列
print(m)
# 将2 修改成888
m[0:1] = 888
print(m)
print(l)
# 这种方法也不会改回来

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[2 4 5]
[888   4   5]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [1]:
import numpy as np
n = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(n)
# 将2、8、11、20取出来
o = n[[0,1,2,3],[1,2,0,4]] # 这种方式没有不包右的问题
print(o)
# 想把2、8、11、20都加上100
# 或者用下面这种方法
p = np.array([1,2,0,4])
n[np.arange(4),p] += 100 # 先把目标锁定，arange读取行数，p读取列数，然后都加上100
print(n)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 2  8 11 20]
[[  1 102   3   4   5]
 [  6   7 108   9  10]
 [111  12  13  14  15]
 [ 16  17  18  19 120]]


In [9]:
# 用布尔值贴标签
import numpy as np
q = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(q)
bool_q_panduan = (q % 2 == 0) # 判断是否为偶数
print(bool_q_panduan) # 这样只是返回是不是偶数
# 可以将所有偶数打印出来
print(q[q % 2 == 0]) # 这样就将偶数打印出来了




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


## array基本运算

In [17]:
# array的相加运算
r = np.array([[1,2],[3,4]],dtype = np.float64)
s = np.array([[5,6],[7,8]],dtype = np.float64)
print(r + s)

[[ 6.  8.]
 [10. 12.]]


In [25]:
# 用函数些一个array的四则运算
class jisuan_array():
    
    def array_jia(self,x,y):
        self.x = x
        self.y =y
        return x + y
    def array_jian(self,x,y):
        self.x = x
        self.y =y
        return x - y
    def array_cheng(self,x,y):
        self.x = x
        self.y =y
        return x * y
    def array_chu(self,x,y):
        self.x = x
        self.y =y
        return x / y
    
rst1 = jisuan_array()
rst_array_jia = rst1.array_jia(np.array([[1,2,3,4],[5,6,7,8]]),np.array([[11,12,13,14],[15,16,17,18]]))
rst_array_jian = rst1.array_jian(np.array([[11,12,13,14],[15,16,17,18]]),np.array([[1,2,3,4],[5,6,7,8]]))
rst_array_cheng = rst1.array_cheng(np.array([[11,12,13,14],[15,16,17,18]]),np.array([[1,2,3,4],[5,6,7,8]]))
rst_array_chu = rst1.array_chu(np.array([[11,12,13,14],[15,16,17,18]]),np.array([[1,2,3,4],[5,6,7,8]]))
print(rst_array_jia)
print(rst_array_jian)
print(rst_array_cheng)
print(rst_array_chu)


[[12 14 16 18]
 [20 22 24 26]]
[[10 10 10 10]
 [10 10 10 10]]
[[ 11  24  39  56]
 [ 75  96 119 144]]
[[11.          6.          4.33333333  3.5       ]
 [ 3.          2.66666667  2.42857143  2.25      ]]


- 矩阵相乘
``` 
 矩阵a = 1 2
        3 4
 矩阵b = 5 6
        7 8
       
 当矩阵a和矩阵b相乘的时候计算规则
 1*5+2*7 1*6+2*8
 3*5+4*7 3*6+4*8
```


In [21]:
# 矩阵相乘举例
# 注意 矩阵 需要是个方形的
import numpy as np
a = np.array([[1,2],[4,5]])
b = np.array([[7,8],[10,11]])
print(a)
print(b)
print(a.dot(b))

[[1 2]
 [4 5]]
[[ 7  8]
 [10 11]]
[[27 30]
 [78 87]]


In [23]:
# 另外一种方法
import numpy as np
a1 = np.array([[1,2],[4,5]])
b1 = np.array([[7,8],[10,11]])
c1 = np.array([[21,33],[24,7]])
rst1 = np.dot(a1,b1,c1)
print(rst1)

[[27 30]
 [78 87]]


In [28]:
# 行求和列求和或计数
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(a)
print(np.sum(a)) # 全部相加
print(np.sum(a,axis = 0)) # axis = 0每一列分别求和
print(np.sum(a,axis = 1)) # axis = 1每一行分别求和

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [3]:
# 变形
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(c.T) # 矩阵翻转 横的变成了竖的

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
# broadcasting
# 正常情况下，两个矩阵进行相加或者相乘或者其他运算，两个矩阵的形状应该是一样的。
# 但是利用broadcasting，两个形状不一样的矩阵也可以进行计算
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([0,1,2])
print(c)
print(c+d)
# 其实如果c和d相加，d会被默认脑补成这个样子 d = np.array([[0,1,2],[0,1,2],[0,1,2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [9]:
# 根据已有数组的形状生成一个新的数组，内容随机
import numpy as np
e = np.array([[110,223,34123],[4123,51,645],[72,81,98]])
print(e)
d = np.empty_like(e)
print(d) # 可以看到d和e的结构是类似的，但是内容不同，虽然是里面内容是有序的，其实是随机生成的

[[  110   223 34123]
 [ 4123    51   645]
 [   72    81    98]]
[[  110   223 34123]
 [ 4123    51   645]
 [   72    81    98]]


## pandas


- 这里有一个数据网站，里面有各种各样的模拟或者真实数据
    - www.kaggle.com

In [9]:
import pandas as pd

# series就相当于列 dataframe就是整个的数据

dingyi_lieming = ['A','B','C','D','E','F','G','H','I'] # 自定定义列名

# header=None 如果首行不是想要的header可以通过这个命令自动加一行，而且他的作用还可以通过坐标轴确定元素位置
# names 自己定义列的名称
df = pd.read_csv("C:\\Users\\Dou\\Desktop\\Python\\Jupyter\\test_file\\kaggle\\diabetes.csv",
                 header=None,names=dingyi_lieming) 
                              
# print(df.head()) # 数据太多打不出来，可以使用head只显示前面的几行（应该有5行）
pd.set_option('display.max_rows',100) # 一些特殊设置，比如是否显示全部数据或者其他的，这里是设置显示行数
pd.set_option('display.max_columns',10) # 这里是设置显示列数
# print(df) # 显示前面几行
# print(df['D']) # 选中df的某一列
# print(df.D) # 这样和上面结果一样，属于简化命令，但是有问题，如果是数字开头的列是不行的，如果是中文的应该也是不行的，而且涉及到关键字也有问题，所以还是应该用上面的
print(df['D'].head())
print(type(df['D'].head())) # 类型是Series
print(df['E'].head())

print("-" * 20)
print(df.A)
print(df.B)
# series可以相加，试一下
print(df.A + df.B) # 根据结果可以看到，实际上是字符串的合并\
print(type(df.A + df.B)) # 类型还是series

0    SkinThickness
1               35
2               29
3                0
4               23
Name: D, dtype: object
<class 'pandas.core.series.Series'>
0    Insulin
1          0
2          0
3          0
4         94
Name: E, dtype: object
--------------------
0      Pregnancies
1                6
2                1
3                8
4                1
          ...     
764             10
765              2
766              5
767              1
768              1
Name: A, Length: 769, dtype: object
0      Glucose
1          148
2           85
3          183
4           89
        ...   
764        101
765        122
766        121
767        126
768         93
Name: B, Length: 769, dtype: object
0      PregnanciesGlucose
1                    6148
2                     185
3                    8183
4                     189
              ...        
764                 10101
765                  2122
766                  5121
767                  1126
768                   193
Lengt

In [14]:
# 生成新的series并加入到dataframe里
new_series = df.A + ',' + df.B
print(new_series)
df['new_series_name'] = new_series # 这里就执行了加入的操作，加入时的名字是new_series_name
print(df) 

0      Pregnancies,Glucose
1                    6,148
2                     1,85
3                    8,183
4                     1,89
              ...         
764                 10,101
765                  2,122
766                  5,121
767                  1,126
768                   1,93
Length: 769, dtype: object
               A        B              C              D        E     F  \
0    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI   
1              6      148             72             35        0  33.6   
2              1       85             66             29        0  26.6   
3              8      183             64              0        0  23.3   
4              1       89             66             23       94  28.1   
..           ...      ...            ...            ...      ...   ...   
764           10      101             76             48      180  32.9   
765            2      122             70             27        0  36.8   
766       

- 为什么调用方法的时候有的时候有括号，有的时候没有括号？
    - 没有括号是特性
    - 右括号的实际是方法

In [3]:
import pandas as pd
pd.set_option("display.max_rows",100)
pd.set_option("display.max_columns",100)
user_title_name = ['A','B','C','D','E','F','G','H','I']
df = pd.read_csv("C:\\Users\\Dou\\Desktop\\Python\\Jupyter\\test_file\\kaggle\\diabetes.csv")
#                  index_col=False,
#                  names = user_title_name,
#                  header=None)
print(df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [4]:
# describe可以显示数据的个数和占比，具体啥的暂时不太清楚，要找个熟悉的数据看一下。
print(df.describe())

       Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  

## 小项目实例

### 随机游走

In [6]:
import random as rd
import math # 计算勾股定理需要使用到math.sqrt
# 思路：先构建一个坐标轴
# 先构建从坐标移动方法
def random_walk(n):
    x = 0
    y = 0
    for i in range(n):
        step = rd.choice(['N','S','W','E']) # 随机选择
        if step == 'N': # 北
            y += 1 
        elif step == 'S': # 南
            y -= 1
        elif step == 'W': # 西
            x -= 1
        else: # 东
            x += 1 
    return x,y
# 开始模拟游走，模拟走10次
for i in range(20): # 模拟循环20次
    one_walk = random_walk(10) # 坐标轴是正10到负10的
    # 这个的意思是计算距离远点有多远
    how_far = round(math.sqrt(int(one_walk[0]) ** 2 + int(one_walk[1]) ** 2),2) # 勾股定理,a² + b² = c² 再使用round保留小数
    if how_far > 40 :
        print("第{}次".format(i+1),one_walk,"太远了已经走了{}".format(how_far))
    else:
        print("第{}次".format(i+1),one_walk,"走了{}继续游荡".format(how_far))
            

第1次 (2, -2) 走了2.83继续游荡
第2次 (-1, -1) 走了1.41继续游荡
第3次 (0, 2) 走了2.0继续游荡
第4次 (6, 2) 走了6.32继续游荡
第5次 (1, 1) 走了1.41继续游荡
第6次 (-1, 3) 走了3.16继续游荡
第7次 (-1, 3) 走了3.16继续游荡
第8次 (1, -3) 走了3.16继续游荡
第9次 (5, 1) 走了5.1继续游荡
第10次 (-1, 1) 走了1.41继续游荡
第11次 (-3, -5) 走了5.83继续游荡
第12次 (2, 2) 走了2.83继续游荡
第13次 (-2, -2) 走了2.83继续游荡
第14次 (0, 4) 走了4.0继续游荡
第15次 (0, -4) 走了4.0继续游荡
第16次 (-3, 3) 走了4.24继续游荡
第17次 (1, 1) 走了1.41继续游荡
第18次 (2, 0) 走了2.0继续游荡
第19次 (0, -2) 走了2.0继续游荡
第20次 (-4, 2) 走了4.47继续游荡


In [7]:
# 上面代码改进
import random as rd
import math # 计算勾股定理需要使用到math.sqrt

# 修缮一下上面的代码 更加高效简洁
def random_walk_v2(n):
    x,y = 0,0 # 简写
    for i in range(n):
        (dx,dy,fx) = rd.choice([(0,1,'北'),(0,-1,'南'),(-1,0,'西'),(1,0,'东')])
        x += dx
        y += dy
    return(x,y,fx)

for i in range(10):
    one_walk = random_walk_v2(20)
    
    print(one_walk,"第{}次".format(i+1),
          # abs是绝对值方法 先平方，然后开方，然后用round保留两位小数
          "当前已经走了{}".format(round(math.sqrt(abs(one_walk[0]) ** 2 + abs(one_walk[1]) ** 2),2)))

(5, 1, '南') 第1次 当前已经走了5.1
(3, 7, '西') 第2次 当前已经走了7.62
(-3, 3, '西') 第3次 当前已经走了4.24
(0, 2, '东') 第4次 当前已经走了2.0
(2, 2, '东') 第5次 当前已经走了2.83
(-1, 1, '南') 第6次 当前已经走了1.41
(-2, -4, '东') 第7次 当前已经走了4.47
(5, 1, '东') 第8次 当前已经走了5.1
(-3, -3, '东') 第9次 当前已经走了4.24
(11, 1, '东') 第10次 当前已经走了11.05


In [18]:
import random as rd
import math # 计算勾股定理需要使用到math.sqrt

# 修缮一下上面的代码 更加高效简洁
def random_walk_v2(n):
    x,y = 0,0 # 简写
    for i in range(n):
        (dx,dy,fx) = rd.choice([(0,1,'北'),(0,-1,'南'),(-1,0,'西'),(1,0,'东')])
        x += dx
        y += dy
    return(x,y,fx)

count_jishu = 0
count_zongshu = 200000

for i in range(count_zongshu): # 模拟循环20次
    one_walk = random_walk_v2(20) # 坐标轴是正10到负10的
    # 这个的意思是计算距离远点有多远
    how_far = round(math.sqrt(int(abs(one_walk[0])) ** 2 + int(abs(one_walk[1])) ** 2),2) # 勾股定理,a² + b² = c² 再使用round保留小数
    if how_far > 5 :
        count_jishu += 1
#        print("第{}次".format(i+1),one_walk,"太远了已经走了{}".format(how_far),"这已经是第{}次了".format(count_jishu))
        
    else:
        pass
# print("第{}次".format(i+1),one_walk,"走了{}继续游荡".format(how_far))
print("喝懵逼的比例是{:.2%}".format(count_jishu/count_zongshu))
# {:.2%} 用来表示百分比，百分号后两位
# 根据输出结果，当前阈值，喝懵逼的比例大概是30%

喝懵逼的比例是30.99%


In [ ]:
# 赌场大小
import random
def suiji_shuzi():
    '''
    随机抽取数字的方法
    '''
    suiji_number = random.randint(1,100)
#    if suiji_number >= 50 :
#        print("{} ---- the number is 1-50".format(suiji_number),end = ' ')
#    else:
#        print("{} ---- the number is 51-100".format(suiji_number),end = ' ')
    return suiji_number
count_jishu = 0
neibujishu = 0
xunhuancishu = 10000
while count_jishu < xunhuancishu:
    count_jishu += 1
    rst1 = suiji_shuzi()
#    print("{}次".format(count_jishu))
    if rst1 > 50:
        neibujishu += 1
print("大于50%的占比是{:.2%}".format(neibujishu/xunhuancishu))

In [19]:
# 赌徒赌场行为

import random

dutu_benjin = 100000 # 倾家荡产搞了10万块用于赌博

print("带着十万块来赌场浪，看看能坚持多久？")
def duchang_guize():
    # 骰子一共三颗
    shaizi_one = random.randint(1,6)
    shaizi_two = random.randint(1,6)
    shaizi_three = random.randint(1,6)
    shaizihe = shaizi_one + shaizi_two + shaizi_three
    kaizhong = 0
    if shaizihe <= 10:
        print("开小。")
    else:
        kaizhong = 1
        print("开大。")
    return kaizhong
jishu_count = 0
while True:
    jishu_count += 1
    meicixiazhu = 10000 # 每次下注10000块
    mai_daxiao = random.randint(0,1) # 0是买小，1是买大
    if mai_daxiao == 0:
        print("我买的是小",end = ',')
    else:
        print("我买的是大",end = ',')
    rst1 = duchang_guize()
    if rst1 == mai_daxiao:
        dutu_benjin += meicixiazhu
        print("赢了！赚了{0}万当前剩{1}万".format(int(meicixiazhu/10000),int(dutu_benjin/10000)),"这是玩的第{}把".format(jishu_count))
        print("-" * 20)
    else:
        dutu_benjin -= meicixiazhu
        print("输了！输了{0}万当前剩{1}万".format(int(meicixiazhu/10000),int(dutu_benjin/10000)),"这是玩的第{}把".format(jishu_count))
        print("-" * 20)
        if dutu_benjin <= 0:
            break

带着十万块来赌场浪，看看能坚持多久？
我买的是小,开大。
输了！输了1万当前剩9万 这是玩的第1把
--------------------
我买的是大,开小。
输了！输了1万当前剩8万 这是玩的第2把
--------------------
我买的是大,开小。
输了！输了1万当前剩7万 这是玩的第3把
--------------------
我买的是大,开小。
输了！输了1万当前剩6万 这是玩的第4把
--------------------
我买的是小,开小。
赢了！赚了1万当前剩7万 这是玩的第5把
--------------------
我买的是小,开大。
输了！输了1万当前剩6万 这是玩的第6把
--------------------
我买的是小,开大。
输了！输了1万当前剩5万 这是玩的第7把
--------------------
我买的是大,开小。
输了！输了1万当前剩4万 这是玩的第8把
--------------------
我买的是大,开大。
赢了！赚了1万当前剩5万 这是玩的第9把
--------------------
我买的是大,开大。
赢了！赚了1万当前剩6万 这是玩的第10把
--------------------
我买的是大,开大。
赢了！赚了1万当前剩7万 这是玩的第11把
--------------------
我买的是小,开大。
输了！输了1万当前剩6万 这是玩的第12把
--------------------
我买的是大,开大。
赢了！赚了1万当前剩7万 这是玩的第13把
--------------------
我买的是小,开小。
赢了！赚了1万当前剩8万 这是玩的第14把
--------------------
我买的是大,开大。
赢了！赚了1万当前剩9万 这是玩的第15把
--------------------
我买的是大,开小。
输了！输了1万当前剩8万 这是玩的第16把
--------------------
我买的是小,开小。
赢了！赚了1万当前剩9万 这是玩的第17把
--------------------
我买的是小,开小。
赢了！赚了1万当前剩10万 这是玩的第18把
--------------------
我买的是大,开小。
输了！输了1万当前剩9万 这是玩的第19把
---

In [ ]:
# 赌博50次 方法比较弱智
import random

dutu_benjin = 100000 # 倾家荡产搞了10万块用于赌博

print("带着十万块来赌场浪，看看能坚持多久？")
def duchang_guize():
    # 骰子一共三颗
    shaizi_one = random.randint(1,6)
    shaizi_two = random.randint(1,6)
    shaizi_three = random.randint(1,6)
    shaizihe = shaizi_one + shaizi_two + shaizi_three
    kaizhong = 0
    if shaizihe <= 10:
        print("开小。")
    else:
        kaizhong = 1
        print("开大。")
    return kaizhong
jishu_count = 0
game_count = 0
while game_count < 50:
    game_count += 1
    jishu_count += 1
    meicixiazhu = 10000 # 每次下注10000块
    mai_daxiao = random.randint(0,1) # 0是买小，1是买大
    if mai_daxiao == 0:
        print("我买的是小",end = ',')
    else:
        print("我买的是大",end = ',')
    rst1 = duchang_guize()
    if rst1 == mai_daxiao:
        dutu_benjin += meicixiazhu
        print("赢了！赚了{0}万当前剩{1}万".format(int(meicixiazhu/10000),int(dutu_benjin/10000)),"这是玩的第{}把".format(jishu_count))
        print("-" * 20)
    else:
        dutu_benjin -= meicixiazhu
        print("输了！输了{0}万当前剩{1}万".format(int(meicixiazhu/10000),int(dutu_benjin/10000)),"这是玩的第{}把".format(jishu_count))
        print("-" * 20)
    if dutu_benjin <=0:
        break
    
if dutu_benjin - 100000 >= 100000:
    print("翻倍了，发财了！")
elif dutu_benjin >= 100000:
    print("算是保本了")
else:
    print("输的就剩裤衩了。")
        

In [1]:
import random
import matplotlib.pyplot as plt
# 赌博规则
def duchang_guize():
    # 骰子一共三颗，这里定义摇骰子规则
    shaizi_one = random.randint(1,6) # 第一颗
    shaizi_two = random.randint(1,6) # 第二颗
    shaizi_three = random.randint(1,6) # 第三颗
    shaizihe = shaizi_one + shaizi_two + shaizi_three # 三颗骰子的和
    if shaizihe <= 10:
        kaidaxiao = 0
    else:
        kaidaxiao = 1
    # 这里去定义输赢规则
    mai_daxiao = random.randint(0,1) # 0是买小，1是买大,随机买
    if mai_daxiao == kaidaxiao:
        rst_maidinglishou = True # 返回True是赢了
    else:
        rst_maidinglishou = False # 返回False是输了
    return rst_maidinglishou

# 赌博行为
print("带着十万块来赌场浪，看看能坚持多久？")
def dubo_xingwei(benjin,xiazhu,cishu):
    count_game = 0
    win_count = 0
    x_la = [] # 赢了还是输了
    y_la = [] # 每次剩的钱
    z_la = [] # 次数计数
    while True:
        z_la.append(count_game+1)
        count_game += 1
        if duchang_guize() == 1:
            benjin += xiazhu
            x_la.append(1)
            y_la.append(benjin)
            win_count += 1
        else:
            benjin -= xiazhu
            x_la.append(0)
            y_la.append(benjin)
        if count_game == cishu or benjin <= 0:
            break
    plt.plot(z_la,y_la)
    return x_la,win_count,benjin,y_la
    
# 开始赌博
#dubo_xingwei(100000,10000,100) #本金10万，每次一万，最多玩100次
# 开始画图-饼图
def dubo_bingtu():
    plt.rcParams['font.sans-serif']=['SimHei'] # 用来防止中文标签乱码
    x = [rst1[0].count(0),rst1[0].count(1)]
    y = ['输','赢']
    col_la = ['blue','yellow']
    plt.title("赌博输赢概率饼状图")
    plt.pie(x,labels=y,startangle=90,shadow=True,colors=col_la,autopct='%1.2f%%',explode=(0,0.1)) 
    # autopct计算百分比 1.2小数点后两位 explode爆炸弹出
    plt.legend()
    plt.show()
    print(rst1[2])
    return None
# dubo_bingtu()

# 此时有5个人 看看他们的命运 到最后剩了多少钱
n = 0
while n <5:
    dubo_xingwei(100000,10000,100)
    n += 1
#plt.rcParams['font.sans-serif']=['SimHei'] # 用来防止中文标签乱码
plt.xlabel("局数")
plt.ylabel("所剩的钱")
plt.title("5个赌徒的100次赌博")
plt.legend()
plt.show

No handles with labels found to put in legend.


带着十万块来赌场浪，看看能坚持多久？


<function matplotlib.pyplot.show(*args, **kw)>

D:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 20010 missing from current font.
  font.set_text(s, 0.0, flags=flags)
D:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 36172 missing from current font.
  font.set_text(s, 0.0, flags=flags)
D:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 24466 missing from current font.
  font.set_text(s, 0.0, flags=flags)
D:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 30340 missing from current font.
  font.set_text(s, 0.0, flags=flags)
D:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 27425 missing from current font.
  font.set_text(s, 0.0, flags=flags)
D:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 21338 missing from c

In [1]:
# 等价鞅 -- 没做完
# 一旦输了就把赌注加倍，直到赢了为止,赢了再恢复初始赌注
import random
import matplotlib.pyplot as plt
# 赌博规则
def duchang_guize():
    # 骰子一共三颗，这里定义摇骰子规则
    shaizi_one = random.randint(1,6) # 第一颗
    shaizi_two = random.randint(1,6) # 第二颗
    shaizi_three = random.randint(1,6) # 第三颗
    shaizihe = shaizi_one + shaizi_two + shaizi_three # 三颗骰子的和
    if shaizihe <= 10:
        kaidaxiao = 0
    else:
        kaidaxiao = 1
    # 这里去定义输赢规则
    mai_daxiao = random.randint(0,1) # 0是买小，1是买大,随机买
    if mai_daxiao == kaidaxiao:
        rst_maidinglishou = True # 返回True是赢了
    else:
        rst_maidinglishou = False # 返回False是输了
    return rst_maidinglishou

def gaoji_dutu(duben,start_dujin,game_count): # 赌本10万，初始每次1万
    now_dujin = start_dujin # 第一的时候本次赌金等于初始赌金
    x = []
    y = []
    now_game_count = 1 # 这是第一轮游戏
    last_game = 1 #假设上一轮游戏是赢得
    last_game_dujin = start_dujin

# <center>正则表达式</center>

In [14]:
# 如何从一个字符串总查找到一串数字，比如查找出身份证和电话号码
import re

message = '''
this is asdfmn  sdlfknalnksdfpoi sodifjlkjn er17377777777,m fdskfjhasdofiuyh mn ,wmenfd,masxdfiautgql,enwr,smad fzxvckzjxdgbfqasdf,mn qwer,mnxzlkfjansdf,m
sdflkha18614045811sldfknas,mdn fwoeiu15381141117fryskj,mdfn bwqeroqiwejflksdmnf.asmn18888888888 dfwebrkuj
sdlfkasjdlfmnwqerfoqief0poiasdf;lknasdnf vqwef
saldkfnas,dn fv,aksednjfl232700199011274190qwikejfwpf.,m.s,dfa
saldfknxz.cv[pqwpoirjtqwlerknm.,wsdfasdfasdfasdfsdf,.mnqw,emfnqdkiuxc;lvmwe,.fqn,wjebfkjbedf
'''
# 上面是一串很烦的东西，我的电话号码和身份证隐藏在其中，我得想办法把他挑出来
my_id_card = re.compile(r"\d\d\d\d\d\d\d\d\d\d\d\d\d\d\d\d\d\d") # 定义身份证的格式 \d是数字，大部分情况下不写r可能没问题，但是最好写上
my_tel_number = re.compile(r"\d\d\d\d\d\d\d\d\d\d\d") # 定义电话格式
rst_id_card = my_id_card.search(message)
rst_tel_number = my_tel_number.search(message)
print(rst_id_card)  # span标明了位置
print(rst_tel_number)
print(rst_id_card.group()) # 出去多余信息，只显示match的信息
print(rst_tel_number.group())

# 但是需要注意，上面这种方法一次只能知道一个指定的字符
rst_tel_all = my_tel_number.findall(message)
print(rst_tel_all) # 可以看到多出来了一个身份证号码和一个17x的不合格的电话

# 假如我想找电话，只看前3位
my_pho_number_yunyingshang = re.compile(r"(\d\d\d)(\d\d\d\d\d\d\d\d)") # 可以通过括号使用
rst_pho_number_yunyingshang = my_pho_number_yunyingshang.search(message)
print(rst_pho_number_yunyingshang.group(1))

<re.Match object; span=(334, 352), match='232700199011274190'>
<re.Match object; span=(47, 58), match='17377777777'>
232700199011274190
17377777777
['17377777777', '18614045811', '15381141117', '18888888888', '23270019901']
173


In [8]:
# 以下为更复杂一点的情况
# 如果里面的电话格式很复杂 比如是 （86）-18614045811这种格式的话
import re
message = '''
this is asdfmn  sdlfknalnksdfpoi sodifjlkjn er17377777777,m fdskfjhasdofiuyh mn ,wmenfd,masxdfiautgql,enwr,smad fzxvckzjxdgbfqasdf,mn qwer,mnxzlkfjansdf,m
sdflkha(86)-18614045811sldfknas,mdn fwoeiu15381141117fryskj,mdfn bwqeroqiwejflksdmnf.asmn18888888888 dfwebrkuj
sdlfkasjdlfmnwqerfoqief0poiasdf;lknasdnf vqwef
saldkfnas,dn fv,aksednjfl232700199011274190qwikejfwpf.,m.s,dfa
saldfknxz.cv[pqwpoirjtqwlerknm.,wsdfasdfasdfasdfsdf,.mnqw,emfnqdkiuxc;lvmwe,.fqn,wjebfkjbedf
'''
my_tel = re.compile(r"(\d\d)-(\d\d\d\d\d\d\d\d\d\d\d)")
rst_tel = my_tel.search(message)
print(rst_tel) # 因为加了86加了括号，所以根本搜索不出来
# print(rst_tel.group(1),rst_tel.group(2))
# 可以定义一个带括号的条件 如下
my_tel_new = re.compile(r"(\(\d\d\))-(\d\d\d\d\d\d\d\d\d\d\d)") # 注意括号的使用
rst_tel_new = my_tel_new.search(message)
print(rst_tel_new.group()) # 这样就可以

None
(86)-18614045811


In [21]:
# 考虑更加复杂的情况
# 如何把153开头的电话都找出来
import re
message = '''
this is asdfmn  sdlfknalnksdfpoi sodifjlkjn er17377777777,m fdskfjhasdofiuyh mn ,wmenfd,masxdfiautgql,enwr,smad fzxvckzjxdgbfqasdf,mn qwer,mnxzlkfjansdf,m
sdflkha(86)-18614045811sldfknas,mdn fwoeiu15381141117fryskj,mdfn bwqeroqiwejflksdmnf.asmn18888888888 dfwebrkuj
sdlfkasjdlfmnwqerfoqief0poiasdf;lknasdnf18977271231 vqwef
saldkfnas,dn fv,aksednjfl232700199011274190qw15382635643ikejfwpf.,m.s,dfa
saldfknxz.cv[pqwpoirjtqwlerknm.,wsdfasdfasdfasdfsdf,.mnqw,emfnqdkiuxc;lvmwe,.fqn,wjebfkjbedf
'''
my_rule_153 = re.compile(r"153(8114|8263)") # 可以利用括号和管道符
rst_rule_153 = my_rule_153.search(message)
print(rst_rule_153.group())

1538114


In [43]:
# 假如有这样一种情况 外国人一般有first name middle name last name，但是中间的名字一般会省略
import re
message = '''
this is asdfmn  sdlfknalnksdfpoi sodifjlkjn er17377777777,m fdskfjhasdofiuyh mn ,wmenfd,masxdfiautgql,enwr,smad fzxvckzjxdgbfqasdf,mn qwer,mnxzlkfjansdf,m
sdflkha(86)-18614045811sTom Hanksldfknas,mdn fwoeiu15381141117fryskj,mdfn bwqeroqiwejflksdmnf.asmn18888888888 dfwebrkuj
sdlfkasjdlfmnwqerfoqief0poiasdf;lknasdnf18977271231 vqwef
saldkfnas,dn fv,aksednjfl232700199011274190qw15382635643ikejfwpf.,m.s,dfa
saldfknxz.cv[pqwpoirjtqwlerknm.,wsdfasdfasdfasdfsdf,.mnqw,emfnqdkiuxc;lvmwe,.fqn,wjebfkjbedf
'''
my_find_name = re.compile(r"Tom (Dodo )?Hanks") # 这里可以通过()?这种方式去做一个可选项，但是要注意空格问题
# 可以把空格加进中间的可选项里
rst_find_name = my_find_name.search(message)
print(rst_find_name.group())

Tom Hanks


In [85]:
import re
text1 = '''
this is asdfmn  sdlfknalnksdfpoi sodifjlkjn er17377777777,m fdskfjhasdofiuyh mn ,wmenfd,masxdfiautgql,enwr,smad fzxvckzjxdgbfqasdf,mn qwer,mnxzlkfjansdf,m
sdflkha(86)-18614045811sTom Hankshello~~~~！~ldfknas,mdn fwoeiu15381141117fryskj,mdfn bwqeroqiwejflksdmnf.asmn18888888888 dfwebrkuj
sdlfkasjdlfmnwqerfoqief0poiasdf;lknasdnf18977271231 vqwef
saldkfnas,dn fv,aksednjfl2327001990112hello~~74190qw15382635643ikejfwpf.,m.s,dfa
saldfknxz.cv[pqwpoirjtqwlerknm.,wsdfasdfasdfasdfsdf,.mnqw,emfnqdkiuxc;lvmwe,.fqn,wjebfkjbedf
'''
my_find_hello = re.compile(r"hello(~)+") # 利用*可以找到很多个可选字符 +也可以
rst_find_hello = my_find_hello.search(text1)
print(rst_find_hello.group())

# 现在有两个波浪线的还有四个波浪线的，怎么把两个波浪线的找出来
my_find_hello_new = re.compile(r"hello(~){2}") # 利用大括号就可以精确找到两个波浪线的字符
rst_find_hello_new = my_find_hello_new.search(text1) 
print(rst_find_hello_new.group())

# 所以当查找电话号码的时候也可以使用上面的方式进行简化
my_find_tel_new = re.compile(r"(\d){11}") # 11个数字
my_rst_tel = my_find_tel_new.search(text1)
print(my_rst_tel)

# 还可以设置字符区间
my_find_tel_new_1 = re.compile(r"(\d){2,8}？") # 2到8个数字 如果不加问好再试一下？ ？带表是不是贪婪的，不加？查到的多，能查到多少个就尽量查找多少个
my_rst_tel_1 = my_find_tel_new_1.search(text1)
print(my_rst_tel_1)

hello~~~~
hello~~
<re.Match object; span=(47, 58), match='17377777777'>
None


In [109]:
# findall的用法
# 在百度网页的源代码中把电话号码找出来
import re
baidu_text = r'''

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="baidu-site-verification" content="m1imKvW1HK" />
  <link rel="shortcut icon" href="/Public/img/favicon.ico" type="image/x-icon">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- Bootstrap CSS -->
  <!-- <link href="https://cdn.bootcss.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no" />
<!-- 删除默认的苹果工具栏和菜单栏 ： 即启用 WebApp 全屏模式  -->
<meta name="apple-mobile-web-app-capable" content="yes" />
<!-- 在web app应用下状态条（屏幕顶部条）的颜色；默认值为default（白色），可以定为black（黑色）和black-translucent（灰色半透明）若值为“black-translucent”将会占据页面px位置，浮在页面上方（会覆盖页面20px高度–iphone4和itouch4的Retina屏幕为40px）。 -->
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<!-- 忽略数字自动识别为电话号码 ,忽略识别邮箱 -->
<meta name="format-detection" content="telephone=no, email=no" />
<!-- 启用360浏览器的极速模式(webkit) -->
<meta name="renderer" content="webkit">
<!-- 避免IE使用兼容模式 -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- uc强制竖屏 -->
<meta name="screen-orientation" content="portrait" />
<!-- QQ强制竖屏 -->
<meta name="x5-orientation" content="portrait">
<!-- UC强制全屏 -->
<meta name="full-screen" content="true" />
<!-- QQ强制全屏 -->
<meta name="x5-fullscreen" content="true" />
<!-- 360强制全屏 -->
<meta name="360-fullscreen" content="true" />
<!-- 站内搜索站点验证 -->
<meta name="baidu-site-verification" content="m1imKvW1HK" />
<link rel="shortcut icon" href="/Public/img/favicon.ico" type="image/x-icon">
<script src="/Public/js/fontbase.js?v=12"></script>
<link href="/Public/css/lib/bootstrap.min.css?v=14" rel="stylesheet">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<link rel="stylesheet" href="/Public/css/common.css?v=16">
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Fb9a77820b2fa17d7223b50a01ab1aa7a' type='text/javascript'%3E%3C/script%3E"));
</script>

  <link href="/Public/css/slick.css?v=12" rel="stylesheet">
  <link href="/Public/css/slick-theme.css?v=12" rel="stylesheet">
  <link rel="stylesheet" href="/Public/css/contactUs.css?v=16">
  <title>联系百度</title>
  <meta name="description" content='总机：(+86 10)5992 8888 TEL: (+86 10)5992 8888传真：(+86 10)5992 0000 FAX:(+86 10)5992 0000'>
  <meta name="keywords" content="百度办公地址、百度联系方式、联系百度、如何联系百度、怎么联系百度">
</head>

<body id="contactUs">
  <div class="main">
    <div class="bd-content-nav nav-show J-bd-nav">
  <div class="section nav-section">
    <div class="nav-box">
      <div class="row">
        <div class="col-sm-2 col-xs-12">
          <a href="/home/index">
            <img src="/Public/img/logo.png?v=15" alt="" class="logo">
          </a>
        </div>
        <div class="col-sm-10 col-xs-12">
          <ul class="bd-nav">
            <li class="nav-bd-link active"><a href="/home/index" target="_blank">关于百度</a></li>
            <li class="nav-bd-link"><a href="//www.baidu.com/more/" target="_blank">关于产品</a></li>
            <li class="nav-bd-link"><a href="/home/index/join_us" target="_blank">加入我们</a></li>
            <li class="nav-bd-link"><a href="/home/index/contact_us" target="_blank">联系我们</a></li>
            <div class="sideline"></div>
          </ul>
        </div>
        <div class="bd-content-fun">
          <div class="home-div">
            <span class="cn-home-link">中文</span>|
            <a href="//ir.baidu.com/phoenix.zhtml?c=188488&p=irol-irhome" class="en-home-link" target="_blank">EN</a>
          </div>
          <script type="text/javascript">(function(){document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E'));var bdcs = document.createElement('script');bdcs.type = 'text/javascript';bdcs.async = true;bdcs.src = 'http://znsv.baidu.com/customer_search/api/js?sid=6706059176758103565' + '&plate_url=' + encodeURIComponent(window.location.href) + '&t=' + Math.ceil(new Date()/3600000);var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(bdcs, s);})();</script>


        </div>
      </div>
    </div>
  </div>
</div>
<div class="h5-nav-bar J-bd-nav">
  <!-- <div class="h5-nav-search-btn"></div> -->
  <div class="logo-box">
    <img src="/Public/img/logo.png?v=15" alt="" class="h5-nav-logo">
  </div>
  <svg id="list" class="h5-nav-toggle-box" width="44" height="44" viewBox="0, 0, 44, 44"></svg>
  <div class="h5-nav-list">
    <a href="/home/index" class="h5-nav h5-active" target="_blank">关于百度</a>
    <a href="//www.baidu.com/more/" class="h5-nav" target="_blank">关于产品</a>
    <a href="/home/index/join_us" class="h5-nav" target="_blank">加入我们</a>
    <a href="/home/index/contact_us" class="h5-nav" target="_blank">联系我们</a>
    <a href="//ir.baidu.com/phoenix.zhtml?c=188488&p=irol-irhome" class="h5-nav" target="_blank">ENGLISH</a>
  </div>
</div>
<div class="h5-nav-mask"></div>

    <div class="main-body">
      <div class="left-box">
        <div class="bg-box hidden-xs">
          <img src="http://static.home.baidu.com/homebd/hmkljbndfacgie1496931590.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A19%3A51Z%2F-1%2F%2Fb22b9cafba3b3aa07aa331fb038d0c6df9eaa1c7aae35bae4281357217f0dba1" class="background">
          <div class="phone-title">
            <p style="text-align: center;"><span style="font-size: 44px;">联系我们</span></p>          </div>
          <div class="contact-phone">
            <p class="phone-num-line">

              <span class="line-ch">总机：(+86 10)5992 8888</span><span class="line-ch">TEL: (+86 10)5992 8888</span><span class="line-ch">传真：(+86 10)5992 0000</span><span class="line-ch">FAX:(+86 10)5992 0000</span>            </p>
          </div>
        <div class="map-content">
            <div class="map-content-title">
              <img src="http://static.home.baidu.com/homebd/bhgdjmlcfkaien1496931694.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A21%3A34Z%2F-1%2F%2Ff26a3d3d9eaa094ed1006bc2efae1f1cd3cf40261cffd6e835704e20d4faec1b" class="map-content-flag">
              <span class="map-content-country">北京</span>
              <p class="map-content-line"></p>
            </div>
            <div class="map-all-box">
                <div data-href="http://map.baidu.com/?newmap=1&amp;ie=utf-8&amp;s=s%26wd%3D%E7%99%BE%E5%BA%A6%E5%A4%A7%E5%8E%A6" class="contact-list">
                  <img src="http://static.home.baidu.com/homebd/jhmlgefinkadbc1496932028.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A27%3A08Z%2F-1%2F%2F3d81f1beeb8a94b113e4fffd76669f666547f9de7d60fd28ebc4126339f92536" class="map-img">
                  <div class="contact-address">
                      百度大厦                      <p style="text-align: left;">北京市海淀区上地十街10号百度大厦<br/></p><p style="text-align: left;">Baidu Campus, No. 10 Shangdi 10th Street, Haidian District, Beijing, China<br/></p><p style="text-align: left;">邮 编：100085<br/></p><p style="text-align: left;">Post Code：100085<br/></p>                  </div>
                </div>
              </div><div class="map-all-box">
                <div data-href="http://map.baidu.com/?newmap=1&amp;ie=utf-8&amp;s=s%26wd%3D%E7%99%BE%E5%BA%A6%E7%A7%91%E6%8A%80%E5%9B%AD" class="contact-list">
                  <img src="http://static.home.baidu.com/homebd/imcefadbhklgjn1496932068.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A27%3A48Z%2F-1%2F%2Fcaa7741d5985e46d3a432c780821ed7b87c966510642a579a7d251b151585f8d" class="map-img">
                  <div class="contact-address">
                      百度科技园                      <p style="text-align: left;">北京市海淀区西北旺东路10号院百度科技园1号楼－5号楼</p><p style="text-align: left;">Baidu Technology Park Building No.1－No.5 No.10 Xibeiwang East Road,Haidian District, Beijing, China</p><p style="text-align: left;">邮 编：100193</p><p style="text-align: left;">Post Code：100193</p>                  </div>
                </div>
              </div><div class="map-all-box">
                <div data-href="http://map.baidu.com/?newmap=1&amp;ie=utf-8&amp;s=s%26wd%3D%E9%B9%8F%E5%AF%B0%E5%9B%BD%E9%99%85%E5%A4%A7%E5%8E%A6" class="contact-list">
                  <img src="http://static.home.baidu.com/homebd/enhgmifdkabclj1496932352.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A32%3A33Z%2F-1%2F%2F7182432f1fbc5b1107c36818ff6fdf8a3909a756747f1311efab5626f881ecd1" class="map-img">
                  <div class="contact-address">
                      鹏寰办公区                      <p style="text-align: left;">北京市海淀区上地东路1号盈创动力园区D座</p><p style="text-align: left;">POWER CREATIVE D, No.1 Shangdi East Road, Haidian District, Beijing, China</p><p style="text-align: left;">邮 编：100085</p><p style="text-align: left;">Post Code：100085</p>                  </div>
                </div>
              </div><div class="map-all-box">
                <div data-href="http://map.baidu.com/?newmap=1&amp;ie=utf-8&amp;s=s%26wd%3D%E8%85%BE%E9%A3%9E%E9%AB%98%E7%A7%91%E5%B2%AD" class="contact-list">
                  <img src="http://static.home.baidu.com/homebd/gdjmeblhancikf1496932567.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A36%3A08Z%2F-1%2F%2Fe1de1cd613b4596d207258579a3168c23a7478cb4c111ff2844c73d4886b9fae" class="map-img">
                  <div class="contact-address">
                      凯龙办公区                      <p style="text-align: left;">北京市海淀区东北旺西路8号中关村软件园17号北楼3层</p><p style="text-align: left;">No.17 Building, Zhongguancun Software Park, 8 Dongbeiwang West Road,Haidian District, Beijing, China</p><p style="text-align: left;">邮 编：100193</p><p style="text-align: left;">Post Code：100193</p>                  </div>
                </div>
              </div>            </div><div class="map-content">
            <div class="map-content-title">
              <img src="http://static.home.baidu.com/homebd/bhgdjmlcfkaien1496931694.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A21%3A34Z%2F-1%2F%2Ff26a3d3d9eaa094ed1006bc2efae1f1cd3cf40261cffd6e835704e20d4faec1b" class="map-content-flag">
              <span class="map-content-country">上海</span>
              <p class="map-content-line"></p>
            </div>
            <div class="map-all-box">
                <div data-href="http://map.baidu.com/?newmap=1&amp;s=inf%26uid%3D70b23e86c6e7113e58f6befd%26wd%3D%E7%99%BE%E5%BA%A6%E4%B8%8A%E6%B5%B7%E7%A0%94%E5%8F%91%E4%B8%AD%E5%BF%83%26all%3D1%26c%3D131&amp;from=alamap&amp;tpl=map_singlepoint" class="contact-list">
                  <img src="http://static.home.baidu.com/homebd/cbnkgjalheifdm1496932591.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A36%3A32Z%2F-1%2F%2F05c732c3a54381182d8e28f51d9709ac2fd4983b5aa9c0f602e1ab35d3d652cc" class="map-img">
                  <div class="contact-address">
                      上海研发中心                      <p style="text-align: left;">上海市浦东新区纳贤路701号百度上研大厦</p><p style="text-align: left;">701 Na Xian Road, Pudong ,Shanghai,China</p><p style="text-align: left;">邮　编：201210</p><p style="text-align: left;">Post Code: 201210</p>                  </div>
                </div>
              </div>            </div><div class="map-content">
            <div class="map-content-title">
              <img src="http://static.home.baidu.com/homebd/bhgdjmlcfkaien1496931694.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A21%3A34Z%2F-1%2F%2Ff26a3d3d9eaa094ed1006bc2efae1f1cd3cf40261cffd6e835704e20d4faec1b" class="map-content-flag">
              <span class="map-content-country">深圳</span>
              <p class="map-content-line"></p>
            </div>
            <div class="map-all-box">
                <div data-href="http://map.baidu.com/?newmap=1&amp;ie=utf-8&amp;s=s%26wd%3D%E6%B7%B1%E5%9C%B3%E5%B8%82%E5%8D%97%E5%B1%B1%E5%8C%BA%E5%AD%A6%E5%BA%9C%E8%B7%AF%E4%B8%9C%E7%99%BE%E5%BA%A6%E5%9B%BD%E9%99%85%E5%A4%A7%E5%8E%A6" class="contact-list">
                  <img src="http://static.home.baidu.com/homebd/fbgdlkacjeihnm1496932612.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A36%3A52Z%2F-1%2F%2Ff1d0e0c33568ee527713199dcce81e2b1914dd30e6c5d1703780febe21eb8d8b" class="map-img">
                  <div class="contact-address">
                      深圳研发中心                      <p style="text-align: left;">深圳市南山区学府路东百度国际大厦</p><p style="text-align: left;">Baidu International Building, Xuefu Road East,Nanshan District,ShenZhen</p><p style="text-align: left;">邮　编：518000</p><p style="text-align: left;">Post Code: 518000</p>                  </div>
                </div>
              </div>            </div><div class="map-content">
            <div class="map-content-title">
              <img src="http://static.home.baidu.com/homebd/jabedcimgnlhkf1496931818.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A23%3A39Z%2F-1%2F%2F88ac2e4ae707978be6afc511c9689042e42c905a1339023839f5d8f2439703bb" class="map-content-flag">
              <span class="map-content-country">森尼韦尔</span>
              <p class="map-content-line"></p>
            </div>
            <div class="map-all-box">
                <div data-href="http://j.map.baidu.com/nDI-e" class="contact-list">
                  <img src="http://static.home.baidu.com/homebd/hicbldjfagknem1496932625.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A37%3A06Z%2F-1%2F%2F1f2c046e3869909b15e4c92eb16664d1b0e727d3e15799650520b01b96c9c5b2" class="map-img">
                  <div class="contact-address">
                      Baidu USA                      <p style="text-align: left;">1195 Bordeaux Drive Sunnyvale</p><p style="text-align: left;">Post Code: CA 94089</p>                  </div>
                </div>
              </div>            </div>

        <div class="foot-box">
          <p class="map-content-line-footer"></p>
          <div class="contact-mail">
            <div class="mail-box">
                <div class="mail-title">
                  合作联系                </div>
                <div class="mail-content">
                  <span class="mail-content-text">
                      市场合作：upmco@baidu.com                  </span><span class="mail-content-text">
                      校园合作：campusmaster@baidu.com                  </span><span class="mail-content-text">
                      战略合作：zhanzhangpingtai@baidu.com                  </span>                </div>
              </div><div class="mail-box">
                <div class="mail-title">
                  业务联系                </div>
                <div class="mail-content">
                  <span class="mail-content-text">
                      百度无线：mbaidu@baidu.com                  </span><span class="mail-content-text">
                      百度推广售后热线：400-921-9999                  </span><span class="mail-content-text">
                      百度推广销售热线：400-800-8888                  </span>                </div>
              </div><div class="mail-box">
                <div class="mail-title">
                  投诉中心                </div>
                <div class="mail-content">
                  <span class="mail-content-text">
                      投诉中心网址： http://help.baidu.com                  </span><span class="mail-content-text">
                      职业道德举报邮箱：bdjb@baidu.com                  </span>                </div>
              </div>          </div>
        </div>
        </div>





      <!-- 移动端 -->
      <div class="m-box visible-xs-block">
        <img src="http://static.home.baidu.com/homebd/hmkljbndfacgie1496931590.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A19%3A51Z%2F-1%2F%2Fb22b9cafba3b3aa07aa331fb038d0c6df9eaa1c7aae35bae4281357217f0dba1" class="m-background">
        <div class="m-phone-title">
          <p style="text-align: center;"><span style="font-size: 44px;">联系我们</span></p>        </div>
        <div class="m-contact-phone">
          <p class="m-phone-num-line">
              <span class="m-line-ch">总机：(+86 10)5992 8888</span><span class="m-line-ch">TEL: (+86 10)5992 8888</span><span class="m-line-ch">传真：(+86 10)5992 0000</span><span class="m-line-ch">FAX:(+86 10)5992 0000</span>          </p>
        </div>

      <div class="m-map-content">
            <div class="m-map-content-title">
              <img src="http://static.home.baidu.com/homebd/bhgdjmlcfkaien1496931694.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A21%3A34Z%2F-1%2F%2Ff26a3d3d9eaa094ed1006bc2efae1f1cd3cf40261cffd6e835704e20d4faec1b" class="m-map-content-flag">
              <span class="m-map-content-country">北京</span>
              <p class="m-map-content-line"></p>
            </div>
          <div class="m-map-all-box">
              <a href="//rc.mbd.baidu.com/zgks4zo">
                <p class="m-address-title">百度大厦</p>
                <img src="http://static.home.baidu.com/homebd/jhmlgefinkadbc1496932028.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A27%3A08Z%2F-1%2F%2F3d81f1beeb8a94b113e4fffd76669f666547f9de7d60fd28ebc4126339f92536" class="m-map-img">
                <div class="m-contact-address">
                      <p style="text-align: left;">北京市海淀区上地十街10号百度大厦<br/></p><p style="text-align: left;">Baidu Campus, No. 10 Shangdi 10th Street, Haidian District, Beijing, China<br/></p><p style="text-align: left;">邮 编：100085<br/></p><p style="text-align: left;">Post Code：100085<br/></p>                </div>
              </a>
            </div><div class="m-map-all-box">
              <a href="//rc.mbd.baidu.com/xx7k3fy">
                <p class="m-address-title">百度科技园</p>
                <img src="http://static.home.baidu.com/homebd/imcefadbhklgjn1496932068.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A27%3A48Z%2F-1%2F%2Fcaa7741d5985e46d3a432c780821ed7b87c966510642a579a7d251b151585f8d" class="m-map-img">
                <div class="m-contact-address">
                      <p style="text-align: left;">北京市海淀区西北旺东路10号院百度科技园1号楼－5号楼</p><p style="text-align: left;">Baidu Technology Park Building No.1－No.5 No.10 Xibeiwang East Road,Haidian District, Beijing, China</p><p style="text-align: left;">邮 编：100193</p><p style="text-align: left;">Post Code：100193</p>                </div>
              </a>
            </div><div class="m-map-all-box">
              <a href="//rc.mbd.baidu.com/x4hpfyf">
                <p class="m-address-title">鹏寰办公区</p>
                <img src="http://static.home.baidu.com/homebd/enhgmifdkabclj1496932352.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A32%3A33Z%2F-1%2F%2F7182432f1fbc5b1107c36818ff6fdf8a3909a756747f1311efab5626f881ecd1" class="m-map-img">
                <div class="m-contact-address">
                      <p style="text-align: left;">北京市海淀区上地东路1号盈创动力园区D座</p><p style="text-align: left;">POWER CREATIVE D, No.1 Shangdi East Road, Haidian District, Beijing, China</p><p style="text-align: left;">邮 编：100085</p><p style="text-align: left;">Post Code：100085</p>                </div>
              </a>
            </div><div class="m-map-all-box">
              <a href="//rc.mbd.baidu.com/vmclz03">
                <p class="m-address-title">凯龙办公区</p>
                <img src="http://static.home.baidu.com/homebd/gdjmeblhancikf1496932567.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A36%3A08Z%2F-1%2F%2Fe1de1cd613b4596d207258579a3168c23a7478cb4c111ff2844c73d4886b9fae" class="m-map-img">
                <div class="m-contact-address">
                      <p style="text-align: left;">北京市海淀区东北旺西路8号中关村软件园17号北楼3层</p><p style="text-align: left;">No.17 Building, Zhongguancun Software Park, 8 Dongbeiwang West Road,Haidian District, Beijing, China</p><p style="text-align: left;">邮 编：100193</p><p style="text-align: left;">Post Code：100193</p>                </div>
              </a>
            </div>        </div><div class="m-map-content">
            <div class="m-map-content-title">
              <img src="http://static.home.baidu.com/homebd/bhgdjmlcfkaien1496931694.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A21%3A34Z%2F-1%2F%2Ff26a3d3d9eaa094ed1006bc2efae1f1cd3cf40261cffd6e835704e20d4faec1b" class="m-map-content-flag">
              <span class="m-map-content-country">上海</span>
              <p class="m-map-content-line"></p>
            </div>
          <div class="m-map-all-box">
              <a href="//rc.mbd.baidu.com/jyo1jvd">
                <p class="m-address-title">上海研发中心</p>
                <img src="http://static.home.baidu.com/homebd/cbnkgjalheifdm1496932591.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A36%3A32Z%2F-1%2F%2F05c732c3a54381182d8e28f51d9709ac2fd4983b5aa9c0f602e1ab35d3d652cc" class="m-map-img">
                <div class="m-contact-address">
                      <p style="text-align: left;">上海市浦东新区纳贤路701号百度上研大厦</p><p style="text-align: left;">701 Na Xian Road, Pudong ,Shanghai,China</p><p style="text-align: left;">邮　编：201210</p><p style="text-align: left;">Post Code: 201210</p>                </div>
              </a>
            </div>        </div><div class="m-map-content">
            <div class="m-map-content-title">
              <img src="http://static.home.baidu.com/homebd/bhgdjmlcfkaien1496931694.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A21%3A34Z%2F-1%2F%2Ff26a3d3d9eaa094ed1006bc2efae1f1cd3cf40261cffd6e835704e20d4faec1b" class="m-map-content-flag">
              <span class="m-map-content-country">深圳</span>
              <p class="m-map-content-line"></p>
            </div>
          <div class="m-map-all-box">
              <a href="//rc.mbd.baidu.com/86vj0xr">
                <p class="m-address-title">深圳研发中心</p>
                <img src="http://static.home.baidu.com/homebd/fbgdlkacjeihnm1496932612.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A36%3A52Z%2F-1%2F%2Ff1d0e0c33568ee527713199dcce81e2b1914dd30e6c5d1703780febe21eb8d8b" class="m-map-img">
                <div class="m-contact-address">
                      <p style="text-align: left;">深圳市南山区学府路东百度国际大厦</p><p style="text-align: left;">Baidu International Building, Xuefu Road East,Nanshan District,ShenZhen</p><p style="text-align: left;">邮　编：518000</p><p style="text-align: left;">Post Code: 518000</p>                </div>
              </a>
            </div>        </div><div class="m-map-content">
            <div class="m-map-content-title">
              <img src="http://static.home.baidu.com/homebd/jabedcimgnlhkf1496931818.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A23%3A39Z%2F-1%2F%2F88ac2e4ae707978be6afc511c9689042e42c905a1339023839f5d8f2439703bb" class="m-map-content-flag">
              <span class="m-map-content-country">森尼韦尔</span>
              <p class="m-map-content-line"></p>
            </div>
          <div class="m-map-all-box">
              <a href="http://j.map.baidu.com/yvPQe">
                <p class="m-address-title">Baidu USA</p>
                <img src="http://static.home.baidu.com/homebd/hicbldjfagknem1496932625.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A37%3A06Z%2F-1%2F%2F1f2c046e3869909b15e4c92eb16664d1b0e727d3e15799650520b01b96c9c5b2" class="m-map-img">
                <div class="m-contact-address">
                      <p style="text-align: left;">1195 Bordeaux Drive Sunnyvale</p><p style="text-align: left;">Post Code: CA 94089</p>                </div>
              </a>
            </div>        </div>        <p class="m-line"></p>
        <div class="m-mail-box">
              <div class="m-mail-title">
                合作联系              </div>
              <div class="m-mail-content">
                <div class="m-mail-content-text">
                      市场合作：upmco@baidu.com                  </div><div class="m-mail-content-text">
                      校园合作：campusmaster@baidu.com                  </div><div class="m-mail-content-text">
                      战略合作：zhanzhangpingtai@baidu.com                  </div>              </div>
            </div><div class="m-mail-box">
              <div class="m-mail-title">
                业务联系              </div>
              <div class="m-mail-content">
                <div class="m-mail-content-text">
                      百度无线：mbaidu@baidu.com                  </div><div class="m-mail-content-text">
                      百度推广售后热线：400-921-9999                  </div><div class="m-mail-content-text">
                      百度推广销售热线：400-800-8888                  </div>              </div>
            </div><div class="m-mail-box">
              <div class="m-mail-title">
                投诉中心              </div>
              <div class="m-mail-content">
                <div class="m-mail-content-text">
                      投诉中心网址： http://help.baidu.com                  </div><div class="m-mail-content-text">
                      职业道德举报邮箱：bdjb@baidu.com                  </div>              </div>
            </div>        <div class="full-section bottom-section">
  <div class="section">
    <div class="bd-home-bottom">
      <div class="bd-bottom-share">
        <span>实时资讯请关注：</span>


        <div class="share-wechat">
                    <img src="http://static.home.baidu.com/homebd/canbfldghejikm1496932813.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A40%3A14Z%2F-1%2F%2Fa795f1f97d12e2a8c9da9862672bd4fec4a887237ec8883e8a3974e9a52b3624" class="share-wechat-img" alt="">
                    <img src="http://static.home.baidu.com/homebd/djkgaclebfhnim1496932814.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A40%3A14Z%2F-1%2F%2F9dfa094e984958f1fefb4c3a95b5f8da3e60c759c30442b2479559bfbcdacf2c" class="share-wechat-qrcode">
                  </div>
                        <a href="http://weibo.com/baiduguanfang?refer_flag=1001030101_&amp;is_hot=1" target="_blank">
                  <img src="http://static.home.baidu.com/homebd/fnejlmkaghcdib1496932842.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A40%3A43Z%2F-1%2F%2F5907b18db08f16dba8613f5117fa9c699a09ac79273e32ef0a1f114b7bdd6e55" alt="">
                </a>                <a href="https://www.facebook.com/BaiduIncorporated" target="_blank">
                  <img src="http://static.home.baidu.com/homebd/ldmfajnhcbkegi1496932864.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A41%3A05Z%2F-1%2F%2F2a180dd88df9a8a7af776fd7239773fab056d1af32cf701e234f5664133a559b" alt="">
                </a>                <a href="https://twitter.com/Baidu_Inc" target="_blank">
                  <img src="http://static.home.baidu.com/homebd/ldgjhfknbaicem1496932883.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A41%3A23Z%2F-1%2F%2F9ec183749754c187c58c2d5b66a8d2f4bd59f6258188aae327addba639a1631d" alt="">
                </a>
      </div>

      <div class="bd-bottom-moremsg">
        <div class="bd-more-msg">合作联系</div>
        <a href="�" class="bd-more-duty bottom-cooperation" target="_blank">�</a><a href="�" class="bd-more-duty bottom-cooperation" target="_blank">�</a><a href="�" class="bd-more-duty bottom-cooperation" target="_blank">�</a>      </div><div class="bd-bottom-moremsg">
        <div class="bd-more-msg">业务联系</div>
        <a href="�" class="bd-more-duty bottom-cooperation" target="_blank">�</a><a href="�" class="bd-more-duty bottom-cooperation" target="_blank">�</a><a href="�" class="bd-more-duty bottom-cooperation" target="_blank">�</a>      </div><div class="bd-bottom-moremsg">
        <div class="bd-more-msg">投诉中心</div>
        <a href="�" class="bd-more-duty bottom-cooperation" target="_blank">�</a><a href="�" class="bd-more-duty bottom-cooperation" target="_blank">�</a>      </div>      <div class="bd-bottom-icp">&copy; Baidu <a href="//www.baidu.com/duty/" target="_blank">使用百度前必读</a> 京ICP证030173号</div>
    </div>
  </div>
</div>

<div class="return-top">
  <img src="/Public/img/return-top.png?v=12" alt="" class="return-img">
</div>
<div class="pc-return">
  <img src="/Public/img/pc-backtop.png?v=12" alt="" class="pc-return-img">
</div>
<div class="mobile-bd-home-bottom">
  <div class="bd-bottom-share">
    <span>实时资讯请关注：</span>



    <div class="share-wechat">
                <img src="http://static.home.baidu.com/homebd/canbfldghejikm1496932813.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A40%3A14Z%2F-1%2F%2Fa795f1f97d12e2a8c9da9862672bd4fec4a887237ec8883e8a3974e9a52b3624" class="share-wechat-img" alt="">
                <img src="http://static.home.baidu.com/homebd/djkgaclebfhnim1496932814.jpg?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A40%3A14Z%2F-1%2F%2F9dfa094e984958f1fefb4c3a95b5f8da3e60c759c30442b2479559bfbcdacf2c" class="m-share-wechat-qrcode">
              </div>
                     <a href="http://weibo.com/baiduguanfang?refer_flag=1001030101_&amp;is_hot=1" target="_blank">
              <img src="http://static.home.baidu.com/homebd/fnejlmkaghcdib1496932842.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A40%3A43Z%2F-1%2F%2F5907b18db08f16dba8613f5117fa9c699a09ac79273e32ef0a1f114b7bdd6e55" alt="">
            </a>           <a href="https://www.facebook.com/BaiduIncorporated" target="_blank">
              <img src="http://static.home.baidu.com/homebd/ldmfajnhcbkegi1496932864.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A41%3A05Z%2F-1%2F%2F2a180dd88df9a8a7af776fd7239773fab056d1af32cf701e234f5664133a559b" alt="">
            </a>           <a href="https://twitter.com/Baidu_Inc" target="_blank">
              <img src="http://static.home.baidu.com/homebd/ldgjhfknbaicem1496932883.png?authorization=bce-auth-v1%2Fe6803def36ae467f81ebdb4bdc75f119%2F2017-06-08T14%3A41%3A23Z%2F-1%2F%2F9ec183749754c187c58c2d5b66a8d2f4bd59f6258188aae327addba639a1631d" alt="">
            </a>
  </div>
  <div class="mobile-flex">
    <div class="mobile-bd-bottom-moremsg mobile-flex-box">
           <div class="mobile-bd-bottom-content">公司介绍<img src="/Public/img/mobile-arrow-up.png?v=12" class="mobile-arrow-up"><img src="/Public/img/mobile-arrow-down.png?v=12" class="mobile-arrow-down"></div>
           <ul class="mobile-bd-detail">
            <li><a href="http://home.baidu.com/home/index/company_culture" target="_blank">核心价值观</a></li><li><a href="http://home.baidu.com/home/index/company" target="_blank">百度简介</a></li><li><a href="http://home.baidu.com/home/index/baidu_road" target="_blank">百度大事记</a></li><li><a href="http://home.baidu.com/home/index/management_team" target="_blank">管理团队</a></li>        </ul>
      </div><div class="mobile-bd-bottom-moremsg mobile-flex-box">
           <div class="mobile-bd-bottom-content">更多信息<img src="/Public/img/mobile-arrow-up.png?v=12" class="mobile-arrow-up"><img src="/Public/img/mobile-arrow-down.png?v=12" class="mobile-arrow-down"></div>
           <ul class="mobile-bd-detail">
            <li><a href="http://csr.baidu.com/" target="_blank">社会责任</a></li><li><a href="http://home.baidu.com/home/index/contact_us" target="_blank">联系我们</a></li>        </ul>
      </div><div class="mobile-bd-bottom-moremsg mobile-flex-box">
           <div class="mobile-bd-bottom-content">商业合作<img src="/Public/img/mobile-arrow-up.png?v=12" class="mobile-arrow-up"><img src="/Public/img/mobile-arrow-down.png?v=12" class="mobile-arrow-down"></div>
           <ul class="mobile-bd-detail">
            <li><a href="http://e.baidu.com/?subsite=bj" target="_blank">百度推广</a></li><li><a href="http://union.baidu.com/customerLogin.html?fromu=http%3A%2F%2Funion.baidu.com%2F" target="_blank">百度联盟</a></li><li><a href="http://pro.baidu.com/" target="_blank">营销中心</a></li>        </ul>
      </div>
  </div>
  <div class="mobile-bd-bottom-icp">&copy; Baidu <a href="//www.baidu.com/duty/" target="_blank">使用百度前必读</a> 京ICP证030173号</div>
</div>
<div class="loading"></div>

      </div>
      </div>
    </div>
  </div>
  <!-- <script src="/Public/js/jquery.min.js"></script> -->
  <script src="/Public/js/lib/jquery.min.js?v=16"></script>
<script src="/Public/js/rem.min.js?v=16"></script>
<script src="/Public/js/lib/bootstrap.min.js?v=16"></script>
<script src="/Public/js/lib/snap.svg-min.js?v=16"></script>
<script src="/Public/js/lib/mustache.min.js?v=16"></script>
<!-- <script src="/Public/js/scroll.js"></script> -->
<script src="/Public/js/common.js?v=16"></script>
<script>
var width = $(window).width();
if (width > 768) {
  window._hmt && window._hmt.push(['_trackEvent', '入口统计','pc端']);
  var height = $(window).height();
  $(window).scroll(function() {
    var top = $(window).scrollTop();
    if (top > height) {
      $(".pc-return").show();
    } else {
      $(".pc-return").hide();
    }
  });
  $("body").on("click", ".pc-return", function() {
    $('body,html').animate({
      scrollTop: 0
    }, 300);
  });
} else {
  window._hmt && window._hmt.push(['_trackEvent', '入口统计','手机端']);
  $(".main").on("click", ".return-img", function() {
    $('body,html').animate({
      scrollTop: 0
    }, 300);
  });
}
</script>
<script type="text/javascript">
var GV = {
  ROOT: "/",
};
</script>

  <script src="/Public/js/slick.min.js?v=13"></script>
  <!-- <script src="/Public/js/index.js"></script> -->
</body>

</html>
'''
# my_find_baidu_tel = re.compile(r"(\d\d\d)-(\d\d\d)-(\d\d\d\d)") # 这种是将每个部分放在元组中
# my_find_baidu_tel = re.compile(r"\d\d\d-\d\d\d-\d\d\d\d") # 正常查找到所有的电话号
my_find_baidu_tel = re.compile(r"(\d){3}-(\d){3}-(\d){4}") # 这种方式就不好用
rst_find_baidu_tel = my_find_baidu_tel.findall(baidu_text)
print(rst_find_baidu_tel)

[('0', '1', '9'), ('0', '0', '8'), ('0', '1', '9'), ('0', '0', '8')]


# <center>爬虫</center>

- 三方库：requests 通过三方库将html内容导入到python

In [1]:
import requests
response1 = requests.get("https://baike.baidu.com/item/%E7%99%BE%E5%BA%A6%E7%99%BE%E7%A7%91/85895?fr=aladdin")
print(response1.apparent_encoding) # 查看当前网页编码
response1.encoding='utf-8' # 为防止乱码，修改读取编码 
print(response1.text) # 查看网页文本

<Response [200]>


- 可以使用Beautiful Soup
    - Beautiful Soup 是一个可以从HTML或XML文件中提取数据的Python库.它能够通过你喜欢的转换器实现惯用的文档导航,查找,修改文档的方式.Beautiful Soup会帮你节省数小时甚至数天的工作时间.

- 一些网站加上后缀robots.txt，这个页面指引了哪些东西可以被爬取，哪些不可以，如果爬的太快可能会被封掉。所以一些网站的反爬机制处理是需要重点解决的问题。

In [ ]:
import requests
from bs4 import BeautifulSoup

# 先用requests把网页提取出来
response1 = requests.get("https://baike.baidu.com/item/%E5%91%A8%E6%9D%B0%E4%BC%A6")
# print(response1.apparent_encoding) # 查看当前网页编码
response1.encoding='utf-8' # 为防止乱码，修改读取编码 
# print(response1.text) # 查看网页文本
soup = BeautifulSoup(response1.content,'html.parser') # 解析的字符串是response1 ，解析内容html.parser
# print(soup) # 全部的网页信息
print(soup.title) # 只打印标题
print(soup.p) # 打印一个段落 不知道为啥百度不行 维基百科可以